HUANG Flora <br>
- Langage : Python <br>
- Système d'exploitation : Windows -> sur Jupyter <br>
- URL de notre fichier d'intérêt: https://www.data.gouv.fr/datasets/localisation-des-pharmacies-dans-openstreetmap <br>
- mise à jour du fichier (pharmacies_points): 09/06/26 <br>
- Date de finalisation du script : **25/06/26** (permet le recalcul Les dates estimées sur les fichiers CSV)

# PARTIE 1 : Création liste des pharmacies de la France métropolitaine 

**Objectif** : scraping de tous les commentaires des pharmacies de la France métropolitaine (hors outre-mer) <br>

**Remarque** : le script de la partie II nécessite l'ouverture de vraie fenêtre visible pour le scraping -> `headless=False` (dans notre cas, il permet de vérifier en temps réel si le scraping a bien été effectué) -> donc pas possible d'utiliser Google Colab

In [3]:
# Installation à faire avant le lancé du projet 
# !pip install pyproj 
# !pip install playwright 
# playwright install chromium

In [4]:
import pandas as pd
liste_pharma = pd.read_csv("pharmacies_point.csv", low_memory=False)
liste_pharma.head(3)

,FID,osm_id,amenity,name,short_name,official_name,alt_name,old_name,operator,operator-type,...,wikipedia,description,opening_hours,source,note,osm_version,osm_timestamp,the_geom,osm_original_geom,osm_type
0,pharmacies_point.4534591198,4534591198,pharmacy,Pharmacie Centrale de Bondy,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Mo-Sa 08:30-19:30,Le ministère des solidarités et de la santé - ...,NaN,7,2024-05-11T16:57:42Z,POINT (276175.8531618072 6260215.629555009),NaN,node
1,pharmacies_point.172156934,172156934,pharmacy,Pharmacie des Andaines,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,cadastre-dgi-fr source : Direction Générale de...,NaN,11,2023-08-18T08:56:31Z,POINT (-40562.0055358363 6204977.067562205),SRID=3857;POLYGON((-40572.837448406004 6204977...,way
2,pharmacies_point.3918927589,3918927589,pharmacy,Pharmacie Cayeux Etaploise,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,"Mo-Fr 08:30-12:30,14:00-19:30; Sa 08:30-12:30,...",Celtipharm - 10/2014,NaN,6,2025-10-09T20:46:23Z,POINT (182438.6302862845 6535708.511748197),NaN,node

In [2]:
liste_pharma.shape

(19137, 44)

In [3]:
liste_pharma.dtypes

FID                   object
osm_id                 int64
amenity               object
name                  object
short_name            object
official_name         object
alt_name              object
old_name              object
operator              object
operator-type         object
dispensing            object
emergency             object
capacity             float64
wheelchair            object
social_facility      float64
ref-FR-FINESS         object
type-FR-FINESS        object
ref-FR-NAF            object
ref-FR-SIRET          object
website               object
contact-website       object
url                   object
phone                 object
contact-phone         object
fax                   object
contact-fax           object
email                 object
contact-email         object
addr-housename        object
addr-housenumber      object
addr-street           object
addr-city             object
addr-postcode         object
wikidata              object
wikipedia             object
description           object
opening_hours         object
source                object
note                  object
osm_version            int64
osm_timestamp         object
the_geom              object
osm_original_geom     object
osm_type              object
dtype: object

Compréhension des variables à travers les sites et différents recherches : 
- https://wiki.openstreetmap.org/wiki/FR:Page_principale <br>
- https://wiki.openstreetmap.org/wiki/FR:%C3%89l%C3%A9ments_cartographiques <br>
- https://wiki.openstreetmap.org/wiki/FR:Tag:amenity%3Dpharmacy <br>
- https://taginfo.geofabrik.de/europe:france/


Variables : 
- **FID** : L'identifiant unique du point sur OpenStreetMap (pour éviter les doublons). 
- osm_id : Le contributeur qui a créé/modifié le point et la date de mise à jour. 
- amenity : //
- **name** : Le nom de la pharmacie 
- short_name : //
- official_name : //
- alt_name  : //
- old_name : //
- operator : //
- operator-type : // 
- dispensing : si la pharmacie peut délivrer des médicament sur ordonnance ou non (yes / no) 
- emergency : 
- capacity : 
- wheelchair : L'accessibilité en fauteuil roulant (yes / no) 
- social_facility : 
- **ref-FR-FINESS** : Le code FINESS national 
- type-FR-FINESS : 
- ref-FR-NAF : 
- **ref-FR-SIRET** : Le numéro SIRET de l'entreprise 
- website :  // 
- contact-website :  // 
- url :  // 
- phone : 
- contact-phone : 
- fax :  // 
- contact-fax :  // 
- email :  // 
- contact-email :  // 
- addr-housename :  // 
- addr-housenumber :  Le numéro dans la rue  
- addr-street : Le nom de la rue 
- addr-city : La commune 
- **addr-postcode** : Le code postal 
- wikidata :  // 
- wikipedia :  // 
- description : 
- opening_hours : Les horaires d'ouverture
- source :  // 
- note : 
- osm_version :  // 
- osm_timestamp :  // 
- **the_geom** : coordonnée en longitude/latitude ou X/Y
- osm_original_geom :  // 
- osm_type :  //

In [4]:
# Sélection des variables pertinantes 
variables_pertinants = ['FID', 'ref-FR-FINESS', 'ref-FR-SIRET','name','addr-city', 'addr-postcode','the_geom']

# Filtrage de la liste pour ne garder que les colonnes qui existent dans notre tableau
colonnes_presentes = [col for col in variables_pertinants if col in liste_pharma.columns]

df_analyse = liste_pharma[colonnes_presentes].copy()

print(df_analyse.shape)
print(df_analyse.head())

(19137, 7)
                            FID ref-FR-FINESS    ref-FR-SIRET  \
0   pharmacies_point.4534591198     930006820             NaN
1    pharmacies_point.172156934     610786485             NaN
2   pharmacies_point.3918927589     620010942  83493738500013
3   pharmacies_point.5101170481     570016774             NaN
4  pharmacies_point.11429216164     610785909  84099976700014

                          name addr-city addr-postcode  \
0  Pharmacie Centrale de Bondy     Bondy         93140
1       Pharmacie des Andaines       NaN           NaN
2   Pharmacie Cayeux Etaploise   Étaples         62630
3           Pharmacie Lorraine       NaN           NaN
4        Pharmacie de la Halle       NaN           NaN

                                      the_geom
0  POINT (276175.8531618072 6260215.629555009)
1  POINT (-40562.0055358363 6204977.067562205)
2  POINT (182438.6302862845 6535708.511748197)
3  POINT (767638.8259116503 6306264.502831527)
4  POINT (69996.83865073131 6234936.366954267)

In [5]:
df_analyse.isnull().sum()

FID                  0
ref-FR-FINESS     1541
ref-FR-SIRET     10960
name              1265
addr-city        14988
addr-postcode    14758
the_geom             0
dtype: int64

Pour la variable "the_geom", on suit la méthode de Nedah -> on sépare les coordonnées de Point(lon, lat) en 2 colonnes : X(longitude) et Y(latitude) <br>
URL : https://github.com/nedahh1/analyse-avis-pharmarcies-grand-est

In [6]:
# Nettoyage et séparation 
nettoye = df_analyse['the_geom'].str.upper().str.replace('POINT (', '', regex=False).str.replace(')', '', regex=False)
df_analyse[['X_mercator', 'Y_mercator']] = nettoye.str.split(' ', expand=True).astype(float)

# On supprime l'ancienne colonne geom
df_analyse = df_analyse.drop(columns=['the_geom'])

# Filtre France métropolitaine adapté au Web Mercator (en incluant valeurs négatifs (ouest))
df_metro = df_analyse[
    (df_analyse['X_mercator'].between(-600000, 1200000)) &  
    (df_analyse['Y_mercator'].between(5000000, 6700000))
].copy()

df_metro.shape

(19137, 8)

Ici on applique un filtrage géographique (= Bounding Box ou boîte de délimitation) : on ne garde que les lignes où la latitude et la longitude sont comprises entre les valeurs données (ci dessus). 
Cela correspond géographiquement au rectangle de la France métropolitaine et éliminer les DOM-TOM (outre-mer) <br>
URL : https://wiki.openstreetmap.org/wiki/Bounding_box

**Web Mercator** : projection cartographique de Mercator utilisée pour les coordonnées dans le système WGS 84 Web Mercatorou WGS 84/Pseudo-Mercator , ainsi que pour la visualisation. <br>
URL : https://en.wikipedia.org/wiki/Web_Mercator_projection#:~:text=However%2C%20the%20Web%20Mercator%20uses,maps%20at%20the%20same%20scale.

Signification des valeurs : coordonnées de distance géographique -> unité appliquée = mètre (m).
- X(-600000, 1200000) : distance par rapport au Méridien de Greenwich (la ligne verticale qui coupe la France vers Bordeaux/Caen)
    - -600 000 mètres (-600 km) : C'est la limite Ouest du rectangle. On va jusqu'à 600 km à l'ouest du méridien pour englober toute la Bretagne (Brest) et le Pays Basque. 
    - 1 200 000 mètres (+1 200 km) : C'est la limite Est. On va jusqu'à 1 200 km à l'est du méridien pour englober Strasbourg, Nice et toute la Corse.

- Y(5000000, 6700000) : axe mesure la distance en ligne droite depuis l'Équateur (la ligne imaginaire au milieu de la Terre)
    - 5 000 000 mètres (5 000 km) : C'est la limite Sud de notre rectangle. La Corse et Perpignan se trouvent à un peu plus de 5 100 km au nord de l'équateur. En démarrant à 5 000 km, on s'assure de ne rien rater au Sud.
    - 6 700 000 mètres (6 700 km) : C'est la limite Nord. Dunkerque se trouve à environ 6 620 km au nord de l'équateur. La barre à 6 700 km permet d'englober tout le nord de la France.
 
Plus d'info concernant la géographie de la France : https://fr.wikipedia.org/wiki/G%C3%A9ographie_de_la_France

In [7]:
df_metro.head()

,FID,ref-FR-FINESS,ref-FR-SIRET,name,addr-city,addr-postcode,X_mercator,Y_mercator
0,pharmacies_point.4534591198,930006820,NaN,Pharmacie Centrale de Bondy,Bondy,93140,276175.853162,6.260216e+06
1,pharmacies_point.172156934,610786485,NaN,Pharmacie des Andaines,NaN,NaN,-40562.005536,6.204977e+06
2,pharmacies_point.3918927589,620010942,83493738500013,Pharmacie Cayeux Etaploise,Étaples,62630,182438.630286,6.535709e+06
3,pharmacies_point.5101170481,570016774,NaN,Pharmacie Lorraine,NaN,NaN,767638.825912,6.306265e+06
4,pharmacies_point.11429216164,610785909,84099976700014,Pharmacie de la Halle,NaN,NaN,69996.838651,6.234936e+06

A partir de nos coordonées en mètre, on essaye de déterminer les BAN (base adresse nationale) des différents pharmacies via le site adresse.data.gouv (site qui permet une convertion automatique des paramètres de coordonnée -> dans notre cas, des coordonnées en mètre en une locatlisation GPS et autres...)<br>
URL : https://adresse.data.gouv.fr/outils

In [8]:
#!pip install pyproj

Ici on va faire appel au site à travers un code pour faire une conversion de nos coordonnées mètres (X/Y) en degrés GPS (lon/lat),
soit EPSG:3857 (Web Mercator) -> EPSG:4326 (GPS standard attendu par la BAN)

**Librairie io** :  pour créer un fichier virtuel temporaire en RAM pour envoyer les données sans encombrer le disque dur. <br>
**Librairie requests** :  pour se connecter à internet pour envoyer les coordonnées et recevoir les réponses de la BAN. <br>
**Librairie pyproj** : pour effectuer des transformations cartographiques et des calculs géodésiques. <br>
**Fonction Transformer** : pour convertir des coordonnées d'un système de cartographie à un autre.

In [9]:
import io 
import requests 
from pyproj import Transformer

In [10]:
transformer = Transformer.from_crs("EPSG:3857", "EPSG:4326", always_xy=True)
df_metro['lon'], df_metro['lat'] = transformer.transform(df_metro['X_mercator'].values, df_metro['Y_mercator'].values)

print("en cours d'envoi...")

# On fait appel à l'API de la BAN 
url_ban = "https://api-adresse.data.gouv.fr/reverse/csv/"
csv_en_texte = df_metro.to_csv(index=False).encode('utf-8')
reponse = requests.post(url_ban, files={'data': ('pharmacies_metro.csv', csv_en_texte)})

if reponse.status_code == 200:
    df_final = pd.read_csv(io.StringIO(reponse.text))
    df_final.to_csv("pharmacies_metropole_final.csv", index=False, sep=";")
    print(" nouveau fichier a été créé.")
else:
    print(f"Erreur de communication avec la BAN. Code erreur : {reponse.status_code}")

en cours d'envoi...
 nouveau fichier a été créé.

status_code :  code de réponse que renvoie n'importe quel site internet quand on l'interroge. <br>
nombre 200 : code universel sur le web pour dire "Succès".

In [11]:
df_final.isnull().sum()

FID                       0
ref-FR-FINESS          1541
ref-FR-SIRET          10960
name                   1265
addr-city             14988
addr-postcode         14758
X_mercator                0
Y_mercator                0
lon                       0
lat                       0
result_longitude      19137
result_latitude       19137
result_distance          54
result_label             54
result_type              54
result_id                54
result_banId           2207
result_housenumber      570
result_name              54
result_street           570
result_postcode          54
result_city              54
result_context           54
result_citycode          54
result_oldcitycode    18061
result_oldcity        18054
result_district       17736
result_status             0
dtype: int64

In [12]:
df_final.head()

,FID,ref-FR-FINESS,ref-FR-SIRET,name,addr-city,addr-postcode,X_mercator,Y_mercator,lon,lat,...,result_name,result_street,result_postcode,result_city,result_context,result_citycode,result_oldcitycode,result_oldcity,result_district,result_status
0,pharmacies_point.4534591198,930006820,NaN,Pharmacie Centrale de Bondy,Bondy,93140,276175.853162,6.260216e+06,2.480930,48.913611,...,26 Avenue Suzanne Buisson,Avenue Suzanne Buisson,93140.0,Bondy,"93, Seine-Saint-Denis, Île-de-France",93010,NaN,NaN,NaN,ok
1,pharmacies_point.172156934,610786485,NaN,Pharmacie des Andaines,NaN,NaN,-40562.005536,6.204977e+06,-0.364375,48.586434,...,53 Rue Félix Desaunay,Rue Félix Desaunay,61600.0,La Ferté Macé,"61, Orne, Normandie",61168,61168.0,La Ferté-Macé,NaN,ok
2,pharmacies_point.3918927589,620010942,83493738500013,Pharmacie Cayeux Etaploise,Étaples,62630,182438.630286,6.535709e+06,1.638874,50.513637,...,32 Place du Général de Gaulle,Place du Général de Gaulle,62630.0,Étaples,"62, Pas-de-Calais, Hauts-de-France",62318,NaN,NaN,NaN,ok
3,pharmacies_point.5101170481,570016774,NaN,Pharmacie Lorraine,NaN,NaN,767638.825912,6.306265e+06,6.895817,49.184730,...,Rue Nationale,NaN,57600.0,Forbach,"57, Moselle, Grand Est",57227,NaN,NaN,NaN,ok
4,pharmacies_point.11429216164,610785909,84099976700014,Pharmacie de la Halle,NaN,NaN,69996.838651,6.234936e+06,0.628792,48.764147,...,19 Rue Saint-jean,Rue Saint-jean,61300.0,L'Aigle,"61, Orne, Normandie",61214,NaN,NaN,NaN,ok

In [13]:
df_final.dtypes

FID                    object
ref-FR-FINESS          object
ref-FR-SIRET           object
name                   object
addr-city              object
addr-postcode          object
X_mercator            float64
Y_mercator            float64
lon                   float64
lat                   float64
result_longitude      float64
result_latitude       float64
result_distance       float64
result_label           object
result_type            object
result_id              object
result_banId           object
result_housenumber     object
result_name            object
result_street          object
result_postcode       float64
result_city            object
result_context         object
result_citycode        object
result_oldcitycode    float64
result_oldcity         object
result_district        object
result_status          object
dtype: object

In [14]:
# Sélection des variables pertinantes 
variables_pertinants2 = ['FID','name','lon', 'lat', 'result_label', 'result_city', 'result_context']

# Filtrage de la liste pour ne garder que les colonnes qui existent dans notre tableau
colonnes_presentes2 = [col for col in variables_pertinants2 if col in df_final.columns]

df_propre = df_final[colonnes_presentes2].copy()

df_propre.head

<bound method NDFrame.head of                                 FID                         name       lon  \
0       pharmacies_point.4534591198  Pharmacie Centrale de Bondy  2.480930
1        pharmacies_point.172156934       Pharmacie des Andaines -0.364375
2       pharmacies_point.3918927589   Pharmacie Cayeux Etaploise  1.638874
3       pharmacies_point.5101170481           Pharmacie Lorraine  6.895817
4      pharmacies_point.11429216164        Pharmacie de la Halle  0.628792
...                             ...                          ...       ...
19132   pharmacies_point.1008156074            Pharmacie Breuzin  0.698130
19133  pharmacies_point.13179599050   Pharmacie de la République  3.035218
19134   pharmacies_point.3712079795         Pharmacie des Arènes  6.187351
19135   pharmacies_point.1933342224            Pharmacie Jacques  6.226526
19136   pharmacies_point.1152714441               Pharmacie Mery  0.694787

             lat                                       result_label  \
0      48.913611              26 Avenue Suzanne Buisson 93140 Bondy
1      48.586434          53 Rue Félix Desaunay 61600 La Ferté Macé
2      50.513637        32 Place du Général de Gaulle 62630 Étaples
3      49.184730                        Rue Nationale 57600 Forbach
4      48.764147                    19 Rue Saint-jean 61300 L'Aigle
...          ...                                                ...
19132  47.338833     Rue des Frères Voisin 37170 Chambray-lès-Tours
19133  50.555092            1a Avenue de la Republique 59113 Seclin
19134  49.111474                        1 Rue de Queuleu 57070 Metz
19135  48.221077               14 Rue Charles Gérome 88270 Dompaire
19136  47.359434  15 Allée du Professeur Guillaume Louis 37200 T...

              result_city                           result_context
0                   Bondy     93, Seine-Saint-Denis, Île-de-France
1           La Ferté Macé                      61, Orne, Normandie
2                 Étaples       62, Pas-de-Calais, Hauts-de-France
3                 Forbach                   57, Moselle, Grand Est
4                 L'Aigle                      61, Orne, Normandie
...                   ...                                      ...
19132  Chambray-lès-Tours  37, Indre-et-Loire, Centre-Val de Loire
19133              Seclin                59, Nord, Hauts-de-France
19134                Metz                   57, Moselle, Grand Est
19135            Dompaire                    88, Vosges, Grand Est
19136               Tours  37, Indre-et-Loire, Centre-Val de Loire

[19137 rows x 7 columns]>

In [15]:
df_propre.isnull().sum()

FID                  0
name              1265
lon                  0
lat                  0
result_label        54
result_city         54
result_context      54
dtype: int64

- 1265 pharmacies dont les noms ne sont pas connus
- 54 pharmacies dont les adresses ne sont pas retrouvées après la conversion

## Vérification
Comparaison du nb de pharmacie par région via notre fiche -> avec la carte régionale des officines de la France par région du site suivant : <br>
URL : https://www.ordre.pharmacien.fr/je-suis/pharmacien/je-suis-pharmacien-titulaire-d-officine/mon-exercice-professionnel/les-cartes <br>
mise à jour 05/06/26.

In [16]:
df_propre['region'] = df_propre['result_context'].str.split(',').str[2].str.strip()

In [17]:
df_propre['region'].value_counts()

region
Île-de-France                 3303
Auvergne-Rhône-Alpes          2353
Nouvelle-Aquitaine            1995
Occitanie                     1904
Hauts-de-France               1749
Provence-Alpes-Côte d'Azur    1705
Grand Est                     1468
Pays de la Loire              1029
Bretagne                       957
Bourgogne-Franche-Comté        955
Normandie                      851
Centre-Val de Loire            702
Corse                          112
Name: count, dtype: int64

In [18]:
df_propre.to_csv("datalistpharma.csv", index=False, sep=";")

Comparaison : 
| regions                        | officine  "OpenstreetMap" | officine "Ordre.pharmacie" |
|--------------------------------|---------------------------|----------------------------|
| Mise à jour                    | 09/06/26                  | 05/06/26                   |
| Ile-de-Fr                      | 3303                      | 3351                       |
| **Auvergne-Rhône-Alpes**       | 2353                      | 2300                       |
| Nouvelle-Aquitaine             | 1995                      | 1973                       |
| Occitanie                      | 1904                      | 1877                       |
| Hautes-de-Fr                   | 1749                      | 1866                       |
| Provence-Alpes-Côte d'Azur     | 1705                      | 1793                       |
| Grand Est                      | 1468                      | 1545                       |
| Pays de la Loire               | 1029                      | 1025                       |
| **Bretagne**                   | 957                       | 947                        |
| **Bourgogne-Franche-Comté**    | 955                       | 869                        |
| Normandie                      | 851                       | 880                        |
| **Centre-val de Loire**        | 702                       | 726                        |
| **Corse**                      | 112                       | 127                        |
| Total                          | 19137                     | 19279                      |


Outil de construction : https://www.tablesgenerator.com/markdown_tables <br>
Remarque : Dans les travaux de Nedah : 1368 officines dans le Grand Est <br>
Dans notre cas avec le fichier mise à jour le 09/06/26 : 1468 offines dans le Grand Est

# Extraction des avis et des réponses 

Ce qui peut nous intéresser : 
- ID/Nom et adresse de la pharmacie.
- Note de l'avis (étoiles).
- Texte de l'avis + Date de publication de l'avis.
- Texte de la réponse de la pharmacie + Date de publication de la réponse (pour calculer le temps de réaction).


Mode d'emploi Playwright : https://playwright.dev/python/docs/intro <br> - librarie plus optimale pour une automatisation de la navigation <br> 
- cependant possible aussi avec Selenium

## PART I : prépa des fichiers csv par région

In [19]:
import os # sert d'interface entre notre code et le système d'exploitation
import unicodedata # permet de manipuler les caractères Unicode

In [20]:
fichier_source = "datalistpharma.csv"
dossier_sortie = "pharmacies_par_region"

os.makedirs(dossier_sortie, exist_ok=True) # permet la création du dossier : pharmacies_par_region

In [21]:
df = pd.read_csv(fichier_source, sep=";")

regions_metropole = [
    "Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Bretagne",
    "Centre-Val de Loire", "Corse", "Grand Est", "Hauts-de-France",
    "Île-de-France", "Normandie", "Nouvelle-Aquitaine", "Occitanie",
    "Pays de la Loire", "Provence-Alpes-Côte d'Azur"]

# Nettoyage des noms de région 
def nom_fichier_safe(region):
    # Supprime les accents
    sans_accents = unicodedata.normalize('NFD', region).encode('ascii', 'ignore').decode('utf-8')
    # Remplace espaces et apostrophes par des underscores + minuscules
    return sans_accents.lower().replace(" ", "_").replace("'", "_").replace("-", "_")

print("découpage par région en cours...")

nom_colonne = "region"

# Boucle de filtrage 
for region in df[nom_colonne].unique():
    if region in regions_metropole:

        df_region = df[df[nom_colonne] == region]

        nom_safe = nom_fichier_safe(region)
        chemin_final = os.path.join(dossier_sortie, f"pharmacies_{nom_safe}.csv")

        df_region.to_csv(chemin_final, index=False, sep=";", encoding="utf-8-sig")
        print(f"Fichier créé : {chemin_final} ({len(df_region)} lignes)")

print("traitement terminé.")

découpage par région en cours...
Fichier créé : pharmacies_par_region\pharmacies_ile_de_france.csv (3303 lignes)
Fichier créé : pharmacies_par_region\pharmacies_normandie.csv (851 lignes)
Fichier créé : pharmacies_par_region\pharmacies_hauts_de_france.csv (1749 lignes)
Fichier créé : pharmacies_par_region\pharmacies_grand_est.csv (1468 lignes)
Fichier créé : pharmacies_par_region\pharmacies_auvergne_rhone_alpes.csv (2353 lignes)
Fichier créé : pharmacies_par_region\pharmacies_pays_de_la_loire.csv (1029 lignes)
Fichier créé : pharmacies_par_region\pharmacies_occitanie.csv (1904 lignes)
Fichier créé : pharmacies_par_region\pharmacies_centre_val_de_loire.csv (702 lignes)
Fichier créé : pharmacies_par_region\pharmacies_provence_alpes_cote_d_azur.csv (1705 lignes)
Fichier créé : pharmacies_par_region\pharmacies_nouvelle_aquitaine.csv (1995 lignes)
Fichier créé : pharmacies_par_region\pharmacies_bourgogne_franche_comte.csv (955 lignes)
Fichier créé : pharmacies_par_region\pharmacies_bretagne.csv (957 lignes)
Fichier créé : pharmacies_par_region\pharmacies_corse.csv (112 lignes)
traitement terminé.

## PART II : Scraping

Afin d'éviter un trop long temps, nous répartissons le scraping de la manière suivante : 


| Flora                   | Louise         | Doriane                    |
|-------------------------|----------------|----------------------------|
| Auvergne Rhône Alpes    | Grand Est      | Nouvelle Aquitaine         |
| Bourgogne-Franche-Comté | Haut de France | Occitanie                  |
| Centre-Val de Loire     | Ile de France  | Pays de la Loire           |
| Bretagne                | Normandie      | Provence-Alpes-Côte d'Azur |
| Corse                   | -              | -                          |

Déroulement du scraping... pour commencer : 
- scraping de 3 communes de notre 1er région : Auvergne-Rhône-Alpes
> pour observer si le rendu est bien fait, si oui
- scraping à l'échelle de la 1er région
- scraping des 4 autres régions 

Application d'un mode asynchrone pour réduire l'intervalle de recherche et d'un temps de pause aléatoires entre chaque recherche de pharmacies pour éviter de se faire bloquer.

In [5]:
#!pip install playwright 
# dans terminal : playwright install

## Scraping pour Google Maps 

### Libraires

In [23]:
import asyncio # exécute plusieurs tâches en même temps
import random  # générer du hasard 
import re # : Sert à chercher, extraire ou modifier du texte de façon très précise
import urllib.parse # Sert à découper, analyser ou formater les adresses de sites internet (URL)

from datetime import datetime, timedelta # Sert à manipuler facilement les dates, les heures, et à calculer des durées
from playwright.async_api import async_playwright

### Fonctions hors Playwright
- pause aléatoire
- conversion date relative en estimée
- construction URL de GoogleMap pour une pharmacie

In [24]:
# Pause aleatoire entre chaque pharmacie (anti-blocage)
async def pause():
    duree = random.uniform(2.0, 5.0)
    await asyncio.sleep(duree)

In [25]:
# Conversion d'une date relative Google en date estimee (AAAA-MM-JJ) dès ajrd

def convertir_date_relative(texte, reference=None):
    if not texte:
        return None

    reference = reference or datetime.now()
    texte = texte.lower().strip()

    if "aujourd" in texte:
        return reference.date().isoformat()
    if "hier" in texte:
        return (reference - timedelta(days=1)).date().isoformat()

    # remplace les nombres ecrits en lettres (un/une) par "1"
    texte = re.sub(r"\b(un|une)\b", "1", texte)

    match = re.search(r"(\d+)\s*(an|annee|mois|semaine|jour|heure|minute)", texte)
    if not match:
        return None

    nombre = int(match.group(1))
    unite = match.group(2)

    if unite in ("an", "annee"):
        delta = timedelta(days=365 * nombre)
    elif unite == "mois":
        delta = timedelta(days=30 * nombre)
    elif unite == "semaine":
        delta = timedelta(weeks=nombre)
    elif unite == "jour":
        delta = timedelta(days=nombre)
    elif unite == "heure":
        delta = timedelta(hours=nombre)
    else:
        delta = timedelta(minutes=nombre)

    return (reference - delta).date().isoformat()

In [26]:
# Construction de l'URL de recherche Google Maps

def construire_url_maps(nom, adresse):
    requete = f"{nom} {adresse}"
    requete_encodee = urllib.parse.quote(requete)
    return f"https://www.google.com/maps/search/{requete_encodee}"

### Nagivation sur une page 
- gestion du popup de cookies
- gestion de la page de resultats multiples (quand plrs etablissements correspondent a la recherche)
- ouverture de l'onglet "avis"

In [27]:
# Fermeture du cookues de consentement
async def accepter_cookies(page):
    textes_possibles = [
        "Tout accepter",
        "Tout refuser",
        "Accepter tout",
        "Accept all",
        "Reject all",
    ]

    for texte in textes_possibles:
        try:
            bouton = page.get_by_role("button", name=texte) # cherhce sur la page internet un bouton qui porte le texte en cours de test.
            if await bouton.count() > 0:
                await bouton.first.click(timeout=3000) # 3s pour clic avt abondon
                await page.wait_for_timeout(1000) # 1s de temps de pause pour laisse bannière disparaitre
                return True
        except Exception:
            continue

    return False

In [28]:
# Clic sur un resultat de la liste de pharmacie 

async def ouvrir_premier_resultat_si_liste(page, nom_recherche=None, max_tentatives=4):
    try:
        for tentative in range(max_tentatives):
            resultats = page.locator("a.hfpxzc") # id CSS pour lien pharmacie
            nb_resultats = await resultats.count()

            if nb_resultats == 0:
                return tentative > 0

            indice_choisi = 0

            # si on connait le nom recherche, on essaie de trouver le 
            # resultat dont le nom correspond le mieux
            if nom_recherche:
                nom_recherche_normalise = nom_recherche.strip().lower()
                for i in range(min(nb_resultats, 10)):
                    try:
                        aria = await resultats.nth(i).get_attribute("aria-label", timeout=1500)
                        if aria and nom_recherche_normalise in aria.strip().lower():
                            indice_choisi = i
                            break
                    except Exception:
                        continue

            await resultats.nth(indice_choisi).click(timeout=5000)
            await page.wait_for_timeout(1800)

            # on verifie si on est arrive sur une vraie fiche : presence
            # des tabs Presentation/Avis/A propos ET plus aucun lien
            # a.hfpxzcdans panneau principal 
            nb_tabs = await page.get_by_role("tab").count()
            nb_liens_restants = await page.locator("div[role='main'] a.hfpxzc").count()

            if nb_tabs >= 3 and nb_liens_restants == 0:
                return True

        return True
    except Exception:
        pass
    return False

In [29]:
# Clic sur le bouton "Avis" de la fiche pharmacie (si present)

async def ouvrir_onglet_avis(page):
    try:
        bouton_avis = page.get_by_role("tab", name=re.compile("avis", re.IGNORECASE))
        await bouton_avis.first.click(timeout=5000)
        return True
    except Exception:
        return False

### Identification du bon panneau et fermeture de modale 

Le code suivant va permettre de forcer le bot à se concentrer uniquement sur la vraie fiche de la pharmacie (en ignorant les listes de résultats qui restent cachées en arrière-plan) et il refermera automatiquement la pop-up de partage si le bot clique dessus par erreur

In [30]:
# Identification du bon div[role='main'] : celui qui correspond a
# la fiche de l'etablissement (aria-label non vide)

async def trouver_panneau_fiche(page):
    panneaux = page.locator("div[role='main']")
    nb_panneaux = await panneaux.count()

    for i in range(nb_panneaux):
        try:
            aria = await panneaux.nth(i).get_attribute("aria-label", timeout=1500)
            nb_liens = await panneaux.nth(i).locator("a.hfpxzc").count()
            if aria and nb_liens == 0:
                return panneaux.nth(i)
        except Exception:
            continue

    # si aucun panneau ne correspond pas exactement au critere,
    # on prend le premier qui n'a pas de liens residuels, ou a defaut
    # le tout premier panneau trouve
    for i in range(nb_panneaux):
        try:
            nb_liens = await panneaux.nth(i).locator("a.hfpxzc").count()
            if nb_liens == 0:
                return panneaux.nth(i)
        except Exception:
            continue

    return panneaux.first

In [31]:
# Fermeture de la fenetre "Partager" si elle s'est ouverte par accident 
async def fermer_modale_partage_si_presente(page):
    try:
        # clic uniquement sur le champ "Lien a partager" avec l'URL maps.app.goo.gl
        champ_lien = page.locator("text=/maps\\.app\\.goo\\.gl/")
        if await champ_lien.count() == 0:
            return False

        # confirmation supplementaire : le bouton "Copier le lien"
        # n'existe que dans cette modale precise
        bouton_copier = page.get_by_text("Copier le lien", exact=False)
        if await bouton_copier.count() == 0:
            return False

        # fermeture via la croix (X) de la modale
        bouton_fermer = page.locator("button[aria-label*='Fermer'], button[aria-label*='Close']")
        if await bouton_fermer.count() > 0:
            await bouton_fermer.first.click(timeout=2000)
            await page.wait_for_timeout(500)
            return True

        return False
    except Exception:
        return False

### Scroll des avis

In [32]:
# Scroll de la liste des avis jusqu'a chargement complet
# scroll de souris = fonction "mouse.wheel"

async def scroller_avis(page, pause_min=0.8, pause_max=1.5, max_tentatives_sans_evolution=10, debug=False):
    nb_avis_precedent = -1
    tentatives_sans_evolution = 0
    await fermer_modale_partage_si_presente(page)
    
    # On utilise trouver_panneau_fiche plutot que .first : une liste
    # de desambiguisation residuelle peut rester presente avec un
    # aria-label vide, et .first capturerait alors le mauvais panneau.
    try:
        panneau = await trouver_panneau_fiche(page)
        boite = await panneau.bounding_box(timeout=3000)
    except Exception:
        boite = None

    if boite:
        # position de scroll : vers le bas du panneau plutot que le
        # centre -> bas du panneau correspond generalement a
        # la zone des avis deja charges
        x_scroll = boite["x"] + boite["width"] / 2
        y_scroll = boite["y"] + boite["height"] - 100
    else:
        x_scroll, y_scroll = 300, 550

    # clic de "réveil" sur le texte d'un avis existant. 
    # Ça évite de cliquer par erreur sur les petits boutons de filtres 
    # (comme "ordonnance" ou "sourire") qui réduiraient la liste des avis 
    x_reveil, y_reveil = None, None
    try:
        zone_texte_avis = page.locator("div[data-review-id] .wiI7pd").first
        if await zone_texte_avis.count() > 0:
            boite_texte = await zone_texte_avis.bounding_box(timeout=2000)
            if boite_texte:
                x_reveil = boite_texte["x"] + min(boite_texte["width"] / 2, 100)
                y_reveil = boite_texte["y"] + boite_texte["height"] / 2
    except Exception:
        pass

    if x_reveil is None:
        x_reveil, y_reveil = x_scroll, y_scroll

        # securite : on verifie que ce point de repli ne tombe pas
        # sur un lien ou un filtre cliquable
        try:
            element_sous_clic = await page.evaluate(f"""
                () => {{
                    const el = document.elementFromPoint({x_reveil}, {y_reveil});
                    if (!el) return null;
                    const lien = el.closest('a.hfpxzc');
                    const bouton = el.closest('button');
                    return (lien || bouton) ? true : false;
                }}
            """)
            if element_sous_clic and boite:
                y_reveil = boite["y"] + 15
        except Exception:
            pass

    # clic de "reveil" avant de commencer le scroll : sur certaines
    # fiches, le panneau a besoin d'un premier clic pour activer le
    # chargement dynamique des avis, avant meme que le scroll ne
    # fasse effet.
    try:
        await page.mouse.click(x_reveil, y_reveil)
        await page.wait_for_timeout(1000)
    except Exception:
        pass

    if debug:
        nb_apres_clic = await page.locator("div[data-review-id]").count()
        print(f"  [debug] apres clic de reveil ({x_reveil:.0f},{y_reveil:.0f}) : {nb_apres_clic} avis")

    # le clic de reveil peut, sur certaines fiches, tomber pile sur
    # un avis deja charge et notamment sur son bouton de partage :
    # on verifie et ferme systematiquement la modale qui en resulterait
    modale_fermee = await fermer_modale_partage_si_presente(page)
    if debug and modale_fermee:
        print("  [debug] une modale de partage a ete fermee apres le clic de reveil")

    while tentatives_sans_evolution < max_tentatives_sans_evolution:
        try:
            for num_geste in range(6):
                await page.mouse.move(x_scroll, y_scroll)
                await page.mouse.wheel(0, 800)
                await asyncio.sleep(0.25)
                if debug:
                    nb_intermediaire = await page.locator("div[data-review-id]").count()
                    print(f"    [debug] apres geste {num_geste+1}/6 : {nb_intermediaire} avis")
        except Exception as e:
            if debug:
                print(f"  [debug] erreur pendant le scroll : {e}")

        modale_fermee = await fermer_modale_partage_si_presente(page)
        if debug and modale_fermee:
            print("  [debug] une modale de partage a ete fermee pendant le scroll")

        await asyncio.sleep(random.uniform(pause_min, pause_max))

        nb_avis_actuel = await page.locator("div[data-review-id]").count()

        if debug:
            print(f"  [debug] cycle (tentatives sans evolution={tentatives_sans_evolution}) : {nb_avis_actuel} avis")

        if nb_avis_actuel <= nb_avis_precedent:
            tentatives_sans_evolution += 1
        else:
            tentatives_sans_evolution = 0

        nb_avis_precedent = nb_avis_actuel

In [33]:
# Clic sur "Plus" si Avis non complet 

async def deplier_texte(bloc_avis, bouton_texte="Plus"):
    try:
        bouton_plus = bloc_avis.get_by_role("button", name=bouton_texte)
        if await bouton_plus.count() > 0:
            await bouton_plus.first.click(timeout=2000)
    except Exception:
        pass

### Extraction des données d'un avis

In [34]:
# Extraction des infos d'un seul bloc d'avis sur Google Maps

async def extraire_un_avis(bloc_avis, reference_date):
    resultat = {
        "review_id": None,
        "note_avis": None,
        "texte_avis": None,
        "date_avis_texte": None,
        "date_avis_estimee": None,
        "texte_reponse": None,
        "date_reponse_texte": None,
        "date_reponse_estimee": None,
    }

    try:
        resultat["review_id"] = await bloc_avis.get_attribute("data-review-id", timeout=2000)
    except Exception:
        pass

    # deplier le texte de l'avis si tronque
    await deplier_texte(bloc_avis, "Plus")

    # note en etoiles : aria-label du type "5 etoiles"
    try:
        bloc_note = bloc_avis.locator("[aria-label*='étoile'], [aria-label*='star']").first
        aria = await bloc_note.get_attribute("aria-label", timeout=2000)
        if aria:
            match_note = re.search(r"(\d+)", aria)
            if match_note:
                resultat["note_avis"] = int(match_note.group(1))
    except Exception:
        pass

    # texte de l'avis
    try:
        texte_avis = await bloc_avis.locator(".wiI7pd").first.inner_text(timeout=2000)
        resultat["texte_avis"] = texte_avis.strip()
    except Exception:
        pass

    # date de publication de l'avis
    try:
        date_avis = await bloc_avis.locator(".rsqaWe").first.inner_text(timeout=2000)
        resultat["date_avis_texte"] = date_avis.strip()
        resultat["date_avis_estimee"] = convertir_date_relative(date_avis, reference_date)
    except Exception:
        pass

    # reponse de la pharmacie (texte + date), bloc distinct s'il existe
    try:
        bloc_reponse = bloc_avis.locator(".CDe7pd").first
        if await bloc_reponse.count() > 0:

            # deplier le texte de la reponse si tronque (bouton "Plus" propre a ce bloc)
            await deplier_texte(bloc_reponse, "Plus")

            # texte complet de la reponse apres depliage
            try:
                texte_reponse = await bloc_reponse.locator(".wiI7pd").first.inner_text(timeout=2000)
                resultat["texte_reponse"] = texte_reponse.strip()
            except Exception:
                pass

            # date de la reponse : Google Maps utilise .DZSIDd dans le bloc reponse,
            # pas .rsqaWe comme pour l'avis — on essaie plusieurs selecteurs connus
            for selecteur_date in [".DZSIDd", ".rsqaWe", "[class*='date']"]:
                try:
                    date_reponse = await bloc_reponse.locator(selecteur_date).first.inner_text(timeout=1500)
                    if date_reponse and date_reponse.strip():
                        resultat["date_reponse_texte"] = date_reponse.strip()
                        resultat["date_reponse_estimee"] = convertir_date_relative(date_reponse, reference_date)
                        break
                except Exception:
                    continue
    except Exception:
        pass

    return resultat

### Scraping complet d'une pharmacie
Combine toutes les etapes precedentes pour une pharmacie : navigation, ouverture des avis, scroll, extraction, avec un retry automatique si le resultat semble incomplet.

In [35]:
# Scraping complet d'une pharmacie : recherche + tous ses avis

async def _tenter_scraper_pharmacie(navigateur, nom, adresse, url, reference_date, pharmacy_id):
    page = await navigateur.new_page()
    avis_collectes = []

    for tentative in range(2):
        try:
            await page.goto(url, timeout=30000)
            # on attend que le reseau soit reellement stable avant de
            # continuer, plutot qu'un delai fixe : sous charge parallele
            # (plusieurs pages simultanees)
            try:
                await page.wait_for_load_state("networkidle", timeout=10000)
            except Exception:
                pass
            break
        except Exception as erreur_reseau:
            if tentative == 0:
                print(f"Nouvelle tentative pour {nom} apres erreur reseau : {erreur_reseau}")
                await asyncio.sleep(5)
            else:
                print(f"Echec definitif sur {nom} (FID {pharmacy_id}) : {erreur_reseau}")
                await page.close()
                return avis_collectes

    try:
        await page.wait_for_timeout(2000)

        await accepter_cookies(page)
        await page.wait_for_timeout(1000)

        await ouvrir_premier_resultat_si_liste(page, nom_recherche=nom)
        await page.wait_for_timeout(1000)

        avis_ouverts = await ouvrir_onglet_avis(page)
        if not avis_ouverts:
            await page.wait_for_timeout(2000)
            avis_ouverts = await ouvrir_onglet_avis(page)

        if not avis_ouverts:
            await page.close()
            return avis_collectes

        await page.wait_for_timeout(1500)

        for _ in range(8):
            nb_blocs_initial = await page.locator("div[data-review-id]").count()
            if nb_blocs_initial > 0:
                break
            try:
                panneau = await trouver_panneau_fiche(page)
                boite = await panneau.bounding_box(timeout=2000)
                if boite:
                    x_init = boite["x"] + boite["width"] / 2
                    y_init = boite["y"] + boite["height"] / 2
                    for _ in range(4):
                        await page.mouse.move(x_init, y_init)
                        await page.mouse.wheel(0, 800)
                        await asyncio.sleep(0.25)
            except Exception:
                pass
            await page.wait_for_timeout(1500)

        await scroller_avis(page)

        blocs_avis = page.locator("div[data-review-id]")
        nb_avis = await blocs_avis.count()

        ids_deja_vus = set()

        for i in range(nb_avis):
            bloc = blocs_avis.nth(i)
            infos_avis = await extraire_un_avis(bloc, reference_date)

            review_id = infos_avis.get("review_id")
            if review_id is not None:
                if review_id in ids_deja_vus:
                    continue
                ids_deja_vus.add(review_id)

            avis_collectes.append({
                "FID": pharmacy_id,
                "nom_pharmacie": nom,
                "adresse_pharmacie": adresse,
                **infos_avis,
            })

    except Exception as erreur:
        print(f"Erreur sur la pharmacie {nom} (FID {pharmacy_id}) : {erreur}")

    finally:
        await page.close()

    return avis_collectes


async def scraper_une_pharmacie(navigateur, ligne_pharmacie, seuil_suspect=10):
    pharmacy_id = ligne_pharmacie.get("FID")
    nom = str(ligne_pharmacie.get("name") or "")
    adresse = str(ligne_pharmacie.get("result_label") or "")

    url = construire_url_maps(nom, adresse)
    reference_date = datetime.now()

    avis_collectes = await _tenter_scraper_pharmacie(navigateur, nom, adresse, url, reference_date, pharmacy_id)

    # si le resultat est exactement au seuil suspect (ici 10) = avis suspect > blocage? 
    # on retente une fois sur une session fraiche avant d'accepter ce resultat comme definitif.
    if len(avis_collectes) == seuil_suspect:
        print(f"  Resultat suspect ({seuil_suspect} avis) pour {nom}, nouvelle tentative...")
        await asyncio.sleep(3)
        nouvelle_tentative = await _tenter_scraper_pharmacie(navigateur, nom, adresse, url, reference_date, pharmacy_id)

        # on garde le meilleur des deux resultats (le plus grand nombre d'avis)
        if len(nouvelle_tentative) > len(avis_collectes):
            avis_collectes = nouvelle_tentative

    return avis_collectes

### Scraping en parallèle de plusieurs pharmacies

In [36]:
# Scraping avec N pages en parallele + sauvegarde 

async def scraper_lot_pharmacies(df_pharmacies, chemin_csv_sortie, nb_pages_parallele=5, mode_ajout=False):
    # securite : on retire les pharmacies sans nom renseigne (NaN ou
    # vide) : car imprecise et risque de scraper un etablissement different
    nb_avant_filtre = len(df_pharmacies)
    df_pharmacies = df_pharmacies[df_pharmacies["name"].notna() & (df_pharmacies["name"].str.strip() != "")].copy()
    nb_ignorees_sans_nom = nb_avant_filtre - len(df_pharmacies)
    if nb_ignorees_sans_nom > 0:
        print(f"{nb_ignorees_sans_nom} pharmacie(s) ignoree(s) car sans nom renseigne.")

    # securite : on retire les doublons de pharmacies en entree
    # (meme nom + meme adresse), pour eviter de scraper deux fois
    df_pharmacies = df_pharmacies.drop_duplicates(subset=["name", "result_label"]).copy()

    # mode_ajout=False : on demarre un nouveau fichier (ecrase l'existant)
    # mode_ajout=True  : on ajoute a la suite d'un fichier deja existant
    #                     (utile pour traiter une region commune par commune)
    fichier_existe_deja = mode_ajout and os.path.exists(chemin_csv_sortie)

    async with async_playwright() as playwright:
        # Remarque : headless=True est detecte et bloque par Google Maps
        # headless=False est la seule configuration fiable confirmee par nos tests.
        navigateur = await playwright.chromium.launch(
            headless=False,
            args=["--no-sandbox"],
        )

        semaphore = asyncio.Semaphore(nb_pages_parallele)

        # utilisation d'une liste pour pouvoir modifier la valeur
        # depuis l'interieur de traiter_une_pharmacie (closure)
        fichier_existe_deja_liste = [fichier_existe_deja]

        async def traiter_une_pharmacie(ligne):
            async with semaphore:
                avis = await scraper_une_pharmacie(navigateur, ligne)
                await pause()

                print(f"Pharmacie {ligne['name']} : {len(avis)} avis recuperes")

                if avis:
                    df_avis = pd.DataFrame(avis)
                    df_avis.to_csv(
                        chemin_csv_sortie,
                        mode="a" if fichier_existe_deja_liste[0] else "w",
                        header=not fichier_existe_deja_liste[0],
                        index=False,
                        sep=";",
                        encoding="utf-8-sig",
                    )
                    fichier_existe_deja_liste[0] = True

                return avis

        taches = [traiter_une_pharmacie(ligne) for _, ligne in df_pharmacies.iterrows()]

        # gather attend que TOUTES les taches soient terminees
        # (avec succes ou erreur) avant de continuer, contrairement
        # a as_completed qui peut laisser des taches en suspens
        # si la boucle est interrompue avant leur tour
        await asyncio.gather(*taches, return_exceptions=True)

        await navigateur.close()

    print(f"Lot traite. Fichier sauvegarde : {chemin_csv_sortie}")

### TEST : 3 communes d'Auvergne-Rhone-Alpes

In [37]:
# df_region_ara = pd.read_csv(
#     "pharmacies_par_region/pharmacies_auvergne_rhone_alpes.csv",
#     sep=";"
# )

# # selection de 3 communes au hasard pour le test
# communes_test = df_region_ara["result_city"].dropna().unique()[:3]
# df_test = df_region_ara[df_region_ara["result_city"].isin(communes_test)].copy()

# print(f"Communes testees : {list(communes_test)}")
# print(f"Nombre de pharmacies dans le test : {len(df_test)}")

# await scraper_lot_pharmacies(
#     df_test,
#     chemin_csv_sortie="avis_test_3_communes.csv",
#     nb_pages_parallele=4,
# )

In [6]:
# # Vérification présence du fichier csv 
# print(os.path.exists("avis_test_3_communes.csv"))
# df_resultat = pd.read_csv("avis_test_3_communes.csv", sep=";", encoding="utf-8-sig")
# print(df_resultat.shape)
# df_resultat.head()

In [39]:
# print("Pharmacies distinctes :", df_resultat["nom_pharmacie"].nunique())
# print("Avis distincts (review_id) :", df_resultat["review_id"].nunique())
# print("Avec note :", df_resultat["note_avis"].notna().sum())
# print("Avec texte avis :", df_resultat["texte_avis"].notna().sum())
# print("Avec réponse :", df_resultat["texte_reponse"].notna().sum())

## Scraping d'une region
Avec sous découpage des grosses communes et reprise automatique en cas de coupure ou plantage du navigateur

In [40]:
def decouper_en_sous_lots(df, taille_max=25):
    """Decoupe un DataFrame en sous-lots de taille_max lignes maximum.
    Pour les grosses communes (Lyon, Paris...), cela limite la duree
    de vie de chaque session navigateur et reduit le risque de crash."""
    sous_lots = []
    for debut in range(0, len(df), taille_max):
        sous_lots.append(df.iloc[debut:debut + taille_max])
    return sous_lots


async def scraper_une_region(fichier_region, fichier_sortie, nb_pages_parallele=5, taille_sous_lot=25):
    df_region = pd.read_csv(fichier_region, sep=";")

    # si le fichier de sortie existe deja (suite a une execution
    # precedente ou une coupure), on recupere les adresses deja
    # traitees pour ne pas refaire le travail
    adresses_deja_faites = set()
    if os.path.exists(fichier_sortie):
        df_existant = pd.read_csv(fichier_sortie, sep=";", encoding="utf-8-sig")
        adresses_deja_faites = set(df_existant["adresse_pharmacie"].dropna().unique())
        print(f"Reprise : {len(adresses_deja_faites)} pharmacies deja traitees, elles seront ignorees.")

    communes = df_region["result_city"].dropna().unique()
    print(f"Region : {fichier_region}")
    print(f"Nombre total de communes : {len(communes)}")

    for indice, commune in enumerate(communes, start=1):

        df_commune = df_region[df_region["result_city"] == commune].copy()
        df_commune = df_commune[~df_commune["result_label"].isin(adresses_deja_faites)]

        if df_commune.empty:
            continue

        print(f"[{indice}/{len(communes)}] Commune : {commune} ({len(df_commune)} pharmacies)")

        # decoupage en sous-lots pour les grosses communes 
        sous_lots = decouper_en_sous_lots(df_commune, taille_sous_lot)

        for num_sous_lot, sous_lot in enumerate(sous_lots, start=1):
            if len(sous_lots) > 1:
                print(f"  Sous-lot {num_sous_lot}/{len(sous_lots)} ({len(sous_lot)} pharmacies)")

            # on retente une fois en cas de plantage du navigateur
            # (TargetClosedError ou autre erreur de session)
            for tentative in range(2):
                try:
                    await scraper_lot_pharmacies(
                        sous_lot,
                        chemin_csv_sortie=fichier_sortie,
                        nb_pages_parallele=nb_pages_parallele,
                        mode_ajout=True,
                    )
                    break
                except Exception as erreur_navigateur:
                    print(f"  Erreur navigateur sur ce sous-lot : {erreur_navigateur}")
                    if tentative == 0:
                        print("  Nouvelle tentative pour ce sous-lot...")
                        await asyncio.sleep(5)
                    else:
                        print("  Sous-lot abandonne apres 2 tentatives, on continue avec le suivant.")

    print(f"Scraping termine pour : {fichier_region}")

## Région 1 : Auvergne-Rhone-Alpes
Estimation du scraping avec un PC portable pour cette région : ~25H

In [41]:
# await scraper_une_region(
#     fichier_region="pharmacies_par_region/pharmacies_auvergne_rhone_alpes.csv",
#     fichier_sortie="avis_auvergne_rhone_alpes.csv",
#     nb_pages_parallele=4,
# )

In [42]:
# # Vérification du fichier csv 
# print(os.path.exists("avis_auvergne_rhone_alpes.csv"))
# df_resultat = pd.read_csv("avis_auvergne_rhone_alpes.csv", sep=";", encoding="utf-8-sig")
# print(df_resultat.shape)
# df_resultat.head()

In [43]:
# print("Pharmacies distinctes :", df_resultat["nom_pharmacie"].nunique())
# print("Avis distincts (review_id) :", df_resultat["review_id"].nunique())
# print("Avec note :", df_resultat["note_avis"].notna().sum())
# print("Avec texte avis :", df_resultat["texte_avis"].notna().sum())
# print("Avec réponse :", df_resultat["texte_reponse"].notna().sum())

In [44]:
# # Verification : nombre de pharmacies a 0 avis et a 10 avis

# def verifier_couverture(fichier_region, fichier_sortie, seuil_suspect=10):
#     df_region = pd.read_csv(fichier_region, sep=";")

#     if not os.path.exists(fichier_sortie):
#         print("Fichier de sortie introuvable.")
#         return

#     df_avis = pd.read_csv(fichier_sortie, sep=";", encoding="utf-8-sig")

#     # nombre d'avis recuperes par pharmacie (cle = adresse)
#     compte_avis = df_avis.groupby("adresse_pharmacie").size()

#     total_pharmacies = df_region["result_label"].nunique()
#     adresses_traitees = set(df_avis["adresse_pharmacie"].dropna().unique())
#     adresses_a_zero = set(df_region["result_label"]) - adresses_traitees
#     adresses_a_dix = set(compte_avis[compte_avis == seuil_suspect].index)
#     adresses_ok = adresses_traitees - adresses_a_dix

#     print(f"Nombre total de pharmacies dans la region : {total_pharmacies}")
#     print(f"Pharmacies a 0 avis (jamais ecrites)        : {len(adresses_a_zero)}")
#     print(f"Pharmacies a exactement {seuil_suspect} avis (suspectes) : {len(adresses_a_dix)}")
#     print(f"Pharmacies correctement scrapees (>10 avis ou <10 reel) : {len(adresses_ok)}")
#     print(f"Total avis collectes dans le fichier          : {len(df_avis)}")

# verifier_couverture(
#     fichier_region="pharmacies_par_region/pharmacies_auvergne_rhone_alpes.csv",
#     fichier_sortie="avis_auvergne_rhone_alpes.csv",
#     seuil_suspect=10,
# )

### Scraping rattrapage
Estimation scraping ~ 6H pour PC portable

> **Cellule de rattrapge à exécuter uniquement pour celle de la région Auvergne (car correction déjà effectuée sur les codes desfonctions précédentes concernant les avis suspects (10) ou 0 avis)** <br>
> avant la correction -> on retrouvait  ~400/2353 pharmacies pour la région Auvergne avec des avis = 0 ou suspects

Remarque : on suppose que des avis = 0 sont dus 
- au nom de la pharmacie qui ne correspond plus au nom actuel
- pharmacies fermées
- pb de scoll à cause des adresses donnant une liste multiple de pharma

Concernant les avis suspects (10) : 
- pb de scoll

In [2]:
# Code rattrapage pour Auvergne

# def identifier_pharmacies_a_reprendre(fichier_region, fichier_sortie, fichier_rattrapage=None, seuil_suspect=10):
#     df_region = pd.read_csv(fichier_region, sep=";")

#     if not os.path.exists(fichier_sortie):
#         print("Aucun fichier de sortie trouve, rien a rattraper.")
#         return df_region.iloc[0:0]

#     df_avis = pd.read_csv(fichier_sortie, sep=";", encoding="utf-8-sig")

#     compte_avis = df_avis.groupby("adresse_pharmacie").size()

#     adresses_jamais_traitees = set(df_region["result_label"]) - set(df_avis["adresse_pharmacie"].dropna().unique())
#     adresses_suspectes = set(compte_avis[compte_avis == seuil_suspect].index)

#     adresses_a_reprendre = adresses_jamais_traitees | adresses_suspectes

#     # securite anti-coupure : on retire les adresses deja presentes
#     # dans le fichier de rattrapage lui-meme, qu'il vienne d'une
#     # execution precedente complete ou interrompue en cours de route
#     adresses_deja_rattrapees = set()
#     if fichier_rattrapage and os.path.exists(fichier_rattrapage):
#         df_rattrapage_existant = pd.read_csv(fichier_rattrapage, sep=";", encoding="utf-8-sig")
#         adresses_deja_rattrapees = set(df_rattrapage_existant["adresse_pharmacie"].dropna().unique())
#         adresses_a_reprendre = adresses_a_reprendre - adresses_deja_rattrapees

#     print(f"Pharmacies jamais traitees (absentes du fichier principal) : {len(adresses_jamais_traitees)}")
#     print(f"Pharmacies avec exactement {seuil_suspect} avis (suspectes) : {len(adresses_suspectes)}")
#     if adresses_deja_rattrapees:
#         print(f"Deja rattrapees lors d'une execution precedente : {len(adresses_deja_rattrapees)} (ignorees)")
#     print(f"Total a reprendre maintenant : {len(adresses_a_reprendre)}")

#     df_a_reprendre = df_region[df_region["result_label"].isin(adresses_a_reprendre)].copy()
#     return df_a_reprendre


# async def rattraper_pharmacies_manquantes(fichier_region, fichier_sortie, fichier_rattrapage, seuil_suspect=10, nb_pages_parallele=5, taille_sous_lot=25):
#     df_a_reprendre = identifier_pharmacies_a_reprendre(fichier_region, fichier_sortie, fichier_rattrapage, seuil_suspect)

#     if df_a_reprendre.empty:
#         print("Rien a rattraper.")
#         return

#     print(f"\nRelance du scraping sur {len(df_a_reprendre)} pharmacies, "
#           f"resultats sauvegardes dans : {fichier_rattrapage}")

#     sous_lots = decouper_en_sous_lots(df_a_reprendre, taille_sous_lot)

#     for num_sous_lot, sous_lot in enumerate(sous_lots, start=1):
#         print(f"Sous-lot {num_sous_lot}/{len(sous_lots)} ({len(sous_lot)} pharmacies)")

#         for tentative in range(2):
#             try:
#                 await scraper_lot_pharmacies(
#                     sous_lot,
#                     chemin_csv_sortie=fichier_rattrapage,
#                     nb_pages_parallele=nb_pages_parallele,
#                     mode_ajout=True,
#                 )
#                 break
#             except Exception as erreur_navigateur:
#                 print(f"Erreur navigateur sur ce sous-lot : {erreur_navigateur}")
#                 if tentative == 0:
#                     print("Nouvelle tentative...")
#                     await asyncio.sleep(5)
#                 else:
#                     print("Sous-lot abandonne apres 2 tentatives, on continue avec le suivant.")

In [46]:
# # Rattrapage

# await rattraper_pharmacies_manquantes(
#     fichier_region="pharmacies_par_region/pharmacies_auvergne_rhone_alpes.csv",
#     fichier_sortie="avis_auvergne_rhone_alpes.csv",
#     fichier_rattrapage="avis_auvergne_rhone_alpes_rattrapage.csv",
#     seuil_suspect=10,
#     nb_pages_parallele=4)

In [47]:
# print(os.path.exists("avis_auvergne_rhone_alpes_rattrapage.csv"))
# df_check = pd.read_csv("avis_auvergne_rhone_alpes_rattrapage.csv", sep=";", encoding="utf-8-sig")
# print(df_check.shape)
# print("Pharmacies distinctes :", df_check["adresse_pharmacie"].nunique())

In [48]:
# # Vérification du scraping total 
# # fichier principal  + rattrapage.

# def verifier_resultat_complet(fichier_region, fichier_sortie, fichier_rattrapage, seuil_suspect=10):
#     df_region = pd.read_csv(fichier_region, sep=";")
#     total_pharmacies = df_region["result_label"].nunique()

#     # on combine les avis du fichier principal et du rattrapage
#     morceaux = []
#     if os.path.exists(fichier_sortie):
#         morceaux.append(pd.read_csv(fichier_sortie, sep=";", encoding="utf-8-sig"))
#     if os.path.exists(fichier_rattrapage):
#         morceaux.append(pd.read_csv(fichier_rattrapage, sep=";", encoding="utf-8-sig"))

#     if not morceaux:
#         print("Aucun fichier trouve.")
#         return

#     df_avis = pd.concat(morceaux, ignore_index=True)

#     # pour chaque adresse, on garde le MEILLEUR nombre d'avis trouve
#     # (utile si le rattrapage a ameliore un resultat du fichier principal)
#     compte_par_adresse = df_avis.groupby("adresse_pharmacie").size()

#     adresses_scrapees = set(compte_par_adresse.index)
#     adresses_manquantes = set(df_region["result_label"]) - adresses_scrapees
#     adresses_a_dix = compte_par_adresse[compte_par_adresse == seuil_suspect]

#     print(f"Nombre total de pharmacies dans la region : {total_pharmacies}")
#     print(f"Pharmacies scrapees avec succes              : {len(adresses_scrapees)}")
#     print(f"Pharmacies manquantes (jamais scrapees)       : {len(adresses_manquantes)}")
#     print(f"Pharmacies avec exactement {seuil_suspect} avis (suspectes) : {len(adresses_a_dix)}")
#     print(f"Total d'avis collectes                        : {len(df_avis)}")


# verifier_resultat_complet(
#     fichier_region="pharmacies_par_region/pharmacies_auvergne_rhone_alpes.csv",
#     fichier_sortie="avis_auvergne_rhone_alpes.csv",
#     fichier_rattrapage="avis_auvergne_rhone_alpes_rattrapage.csv",
#     seuil_suspect=10,
# )

In [51]:
# # concat des 2 fichiers de notre région Auvergne 
# df_principal = pd.read_csv("avis_auvergne_rhone_alpes.csv", sep=";", encoding="utf-8-sig")
# df_rattrapage = pd.read_csv("avis_auvergne_rhone_alpes_rattrapage.csv", sep=";", encoding="utf-8-sig")

# df_final = pd.concat([df_principal, df_rattrapage], ignore_index=True)

# print("Principal :", len(df_principal), "lignes")
# print("Rattrapage :", len(df_rattrapage), "lignes")
# print("Total fusionne :", len(df_final), "lignes")

# df_final.to_csv("avis_auvergne_rhone_alpes_FINAL.csv", sep=";", index=False, encoding="utf-8-sig")

Principal : 104274 lignes
Rattrapage : 39386 lignes
Total fusionne : 143660 lignes

In [61]:
df_region = pd.read_csv("pharmacies_par_region/pharmacies_auvergne_rhone_alpes.csv", sep=";")
df_avis = pd.read_csv("avis_auvergne_rhone_alpes_FINAL.csv", sep=";", encoding="utf-8-sig")

total_pharmacies = df_region["result_label"].nunique()
compte_par_adresse = df_avis.groupby("adresse_pharmacie").size()
adresses_scrapees = set(compte_par_adresse.index)
nb_scrapees = len(adresses_scrapees)
nb_avec_0_avis = total_pharmacies - nb_scrapees
nb_avec_10_avis = (compte_par_adresse == 10).sum()

print("Total pharmacies :", total_pharmacies)
print(f"Pharmacies scrapees : {nb_scrapees} / {total_pharmacies}")
print("Pharmacies avec 0 avis :", nb_avec_0_avis)
print("Pharmacies avec exactement 10 avis :", nb_avec_10_avis)

Total pharmacies : 2345
Pharmacies scrapees : 2272 / 2345
Pharmacies avec 0 avis : 73
Pharmacies avec exactement 10 avis : 10

Remarque : si y a du temps, supprimer les noms/prénoms mentionnés dans les commentaires (> éthique + RGPD)

## Region 2 : Bourgogne-Franche-Comte

In [53]:
await scraper_une_region(
    fichier_region="pharmacies_par_region/pharmacies_bourgogne_franche_comte.csv",
    fichier_sortie="avis_bourgogne_franche_comte.csv",
    nb_pages_parallele=4,
)

Region : pharmacies_par_region/pharmacies_bourgogne_franche_comte.csv
Nombre total de communes : 489
[1/489] Commune : Sens (10 pharmacies)
Pharmacie Pharmacie Ragot : 5 avis recuperes
Pharmacie Pharmacie Fourre Sangare : 21 avis recuperes
Pharmacie Pharmacie de l'Europe : 37 avis recuperes
Pharmacie Pharmacie d'Abraham : 94 avis recuperes
Pharmacie Pharmacie des Chaillots : 98 avis recuperes
Pharmacie Pharmacie Voulx : 61 avis recuperes
Pharmacie Pharmacie Lafayette de la cathédrale : 108 avis recuperes
Pharmacie Pharmacie Pierre de Coubertin : 81 avis recuperes
Pharmacie Pharmacie Croquet Vicherat : 52 avis recuperes
Pharmacie Pharmacie Champbertrand : 38 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[2/489] Commune : Nevers (15 pharmacies)
2 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Saint-Benin : 0 avis recuperes
Pharmacie Pharmacie Beaume Bechtel : 12 avis recuperes
Pharmacie Pharmacie Delgutte : 1 avis recuperes
Pharmacie Pharmacie Carnot : 40 avis recuperes
Pharmacie Pharmacie Bernamont : 48 avis recuperes
Pharmacie Pharmacie Danchaud Gérard : 2 avis recuperes
Pharmacie Pharmacie Fontaine : 8 avis recuperes
Pharmacie Pharmacie Theuriot : 78 avis recuperes
Pharmacie Pharmacie du Mouesse : 23 avis recuperes
Pharmacie Pharmacie des Montots : 23 avis recuperes
Pharmacie Pharmacie Barathé Tabourin : 28 avis recuperes
Pharmacie Pharmacie Chaméane : 44 avis recuperes
Pharmacie Pharmacie Colbert : 52 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[3/489] Commune : Villeneuve-l'Archevêque (1 pharmacies)
Pharmacie Pharmacie Ferrand : 25 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[4/489] Commune : Cosne-Cours-sur-Loire (4 pharmacies)
Pharmacie Pharmacie Régionale du Val de Loire : 20 avis recuperes
Pharmacie Pharmacie Centrale Mr Vandevyver Mme Birnie Scott Mr Davenne : 86 avis recuperes
Pharmacie Pharmacie Nivernaise : 42 avis recuperes
Pharmacie Pharmacie Saint-Laurent : 51 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[5/489] Commune : Saint-Loup-sur-Semouse (2 pharmacies)
2 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[6/489] Commune : Corre (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[7/489] Commune : Chalon-sur-Saône (22 pharmacies)
Pharmacie Pharmacie Vendramini : 0 avis recuperes
  Resultat suspect (10 avis) pour Pharmacie Cortier, nouvelle tentative...
Pharmacie Pharmacie Dumaine : 43 avis recuperes
Pharmacie Pharmacie de l'Île : 22 avis recuperes
Pharmacie Pharmacie Cortier : 10 avis recuperes
Pharmacie Pharmacie Billoud : 37 avis recuperes
Pharmacie Grande Pharmacie de Paris : 54 avis recuperes
Pharmacie Pharmacie Chaussard : 61 avis recuperes
Pharmacie Pharmacie Noblat : 4 avis recuperes
Pharmacie Pharmacie de l'Hôtel de Ville : 90 avis recuperes
Pharmacie Pharmacie Saint-Vincent : 52 avis recuperes
Pharmacie Pharmacie du Colisée : 48 avis recuperes
Pharmacie Pharmacie Couetoux : 41 avis recuperes
Pharmacie Pharmacie de l'Europe : 0 avis recuperes
Pharmacie Pharmacie Froger Strich : 0 avis recuperes
Pharmacie Pharmacie de l'Obélisque : 25 avis recuperes
Pharmacie Pharmacie des Prés Saint-Jean : 64 avis recuperes
Pharmacie Pharmacie du Palais : 47 avis recuperes
Pharmacie Pharmacie de la Tour : 9 avis recuperes
Pharmacie Pharmacie Laënnec : 15 avis recuperes
Pharmacie Pharmacie des Arts : 35 avis recuperes
Pharmacie Pharmacie Bukwa Balligand : 24 avis recuperes
Pharmacie Grande Pharmacie Lafayette de la Gare : 182 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[8/489] Commune : Châtillon-en-Bazois (1 pharmacies)
  Resultat suspect (10 avis) pour Pharmacie Collin Delaquerrière, nouvelle tentative...
Pharmacie Pharmacie Collin Delaquerrière : 10 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[9/489] Commune : Gergy (1 pharmacies)
Pharmacie Pharmacie des Huiliers : 14 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[10/489] Commune : Bavilliers (2 pharmacies)
Pharmacie Pharmacie de la Douce : 25 avis recuperes
Pharmacie Pharmacie Fourny : 37 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[11/489] Commune : Montbard (4 pharmacies)
2 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Labbé : 0 avis recuperes
Pharmacie Pharmacie Buffon : 11 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[12/489] Commune : Neuilly-Crimolois (1 pharmacies)
Pharmacie Pharmacie Flouriot : 26 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[13/489] Commune : Roppe (1 pharmacies)
Pharmacie Pharmacie de la Baroche : 23 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[14/489] Commune : Andelnans (1 pharmacies)
Pharmacie Pharmacie Marcoux Bildstein : 84 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[15/489] Commune : Dijon (51 pharmacies)
  Sous-lot 1/3 (25 pharmacies)
Pharmacie Pharmacie des Allées : 22 avis recuperes
Pharmacie Pharmacie des Roches d'Or : 38 avis recuperes
Pharmacie Grande Pharmacie Dijonnaise : 51 avis recuperes
Pharmacie L'Officine des Naturalistes : 119 avis recuperes
Pharmacie Pharmacie du Val d'Or : 38 avis recuperes
Pharmacie Grande pharmacie Bruant : 227 avis recuperes
Pharmacie Pharmacie Montchapet : 38 avis recuperes
Pharmacie Pharmacie Lanternier : 13 avis recuperes
Pharmacie Pharmacie Pascal : 49 avis recuperes
Pharmacie Pharmacie des Sciences : 80 avis recuperes
Pharmacie Pharmacie du Drapeau : 100 avis recuperes
Pharmacie Pharmacie Saint-Pierre : 27 avis recuperes
Pharmacie Les Trois Pharmaciens : 12 avis recuperes
Pharmacie Pharmacie Auxonne Wilson : 70 avis recuperes
Pharmacie Pharmacie Santé et Nature : 36 avis recuperes
Pharmacie Pharmacie des Bourroches : 209 avis recuperes
Pharmacie Pharmacie 2000 : 34 avis recuperes
Pharmacie Pharmacie Mansart : 35 avis recuperes
Pharmacie Pharmacie Eiffel : 52 avis recuperes
Pharmacie Pharmacie de la Gare : 60 avis recuperes
Pharmacie Pharmacie Saint-Michel : 40 avis recuperes
Pharmacie Pharmacie des Valendons : 16 avis recuperes
Pharmacie Pharmacie des Perrières : 78 avis recuperes
Pharmacie Pharmacie des Congrès : 35 avis recuperes
Pharmacie Pharmacie Centrale : 66 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
  Sous-lot 2/3 (25 pharmacies)
Pharmacie Pharmacie Bossuet : 39 avis recuperes
Pharmacie Pharmacie des Arts : 71 avis recuperes
Pharmacie Pharmacie Thévenot : 43 avis recuperes
Pharmacie Pharmacie Point Médical : 193 avis recuperes
Pharmacie Pharmacie De La Source : 32 avis recuperes
Pharmacie Pharmacie de la Liberté : 302 avis recuperes
Pharmacie Pharmacie de la République : 86 avis recuperes
Pharmacie Lafayette : 179 avis recuperes
Pharmacie Pharmacie Jaurès : 40 avis recuperes
Pharmacie Pharmacie Giphar du Bocage : 91 avis recuperes
Pharmacie Pharmacie Cap Nord : 23 avis recuperes
Pharmacie Pharmacie de l'Université : 53 avis recuperes
Pharmacie Pharmacie de Jouvence : 57 avis recuperes
Pharmacie Pharmacie du Canal : 76 avis recuperes
Pharmacie Pharmacie Poincaré : 64 avis recuperes
Pharmacie Pharmacie de la Colombière : 49 avis recuperes
Pharmacie Pharmacie du 1er mai : 57 avis recuperes
Pharmacie Pharmacie Sari : 34 avis recuperes
Pharmacie Pharmacie Clemenceau : 37 avis recuperes
Pharmacie Pharmacie de la Combe à la Serpent : 18 avis recuperes
Pharmacie Pharmacie Victor Hugo : 39 avis recuperes
Pharmacie Pharmacie de l'Arquebuse : 44 avis recuperes
Pharmacie Pharmacie du Petit Citeaux : 29 avis recuperes
Pharmacie Pharmacie du Siècle : 222 avis recuperes
Pharmacie Pharmacie de la Toison d'Or : 277 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
  Sous-lot 3/3 (1 pharmacies)
Pharmacie Pharmacie du Lac : 6 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[16/489] Commune : Jussey (2 pharmacies)
Pharmacie Pharmacie Jacquinot : 16 avis recuperes
Pharmacie Pharmacie du Pays Jusséen : 24 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[17/489] Commune : Cercy-la-Tour (2 pharmacies)
Pharmacie Pharmacie Bureau : 3 avis recuperes
Pharmacie Pharmacie BAL LECOINTE : 34 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[18/489] Commune : Cronat (1 pharmacies)
Pharmacie Pharmacie Blond : 8 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[19/489] Commune : Arbois (3 pharmacies)
Pharmacie Pharmacie Greset : 13 avis recuperes
Pharmacie Pharmacie Gay : 12 avis recuperes
Pharmacie Pharmacie Schroll : 12 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[20/489] Commune : Breuches (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[21/489] Commune : Dornes (1 pharmacies)
Pharmacie Pharmacie TROUART : 16 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[22/489] Commune : Morteau (3 pharmacies)
Pharmacie Pharmacie Pierre et Bassetti : 29 avis recuperes
Pharmacie Pharmacie de la Fontaine : 40 avis recuperes
Pharmacie Pharmacie Principale : 126 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[23/489] Commune : Grandvillars (1 pharmacies)
Pharmacie Pharmacie Caillet : 0 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[24/489] Commune : Les Premiers Sapins (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[25/489] Commune : Beaucourt (1 pharmacies)
Pharmacie Pharmacie de Beaucourt : 29 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[26/489] Commune : Héry (1 pharmacies)
Pharmacie Pharmacie de Hery : 28 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[27/489] Commune : Offemont (2 pharmacies)
Pharmacie Ma Pharmacie : 28 avis recuperes
Pharmacie Pharmacie des Forges : 24 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[28/489] Commune : Lucenay-l'Évêque (1 pharmacies)
Pharmacie Pharmacie du Ternin : 23 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[29/489] Commune : Champs-sur-Yonne (1 pharmacies)
Pharmacie Pharmacie de Champs : 35 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[30/489] Commune : Audincourt (7 pharmacies)
Pharmacie Pharmacie Centrale : 13 avis recuperes
Pharmacie Pharmacie Pourtier : 48 avis recuperes
Pharmacie Pharmacie Dieny : 60 avis recuperes
Pharmacie Pharmacie des Acacias : 48 avis recuperes
Pharmacie Pharmacie Malfroy - Pharmacie de la Mairie : 60 avis recuperes
Pharmacie Pharmacie Knittel : 21 avis recuperes
Pharmacie Pharmacie des Forges : 171 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[31/489] Commune : Trévenans (1 pharmacies)
Pharmacie Pharmacie du Viaduc : 42 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[32/489] Commune : Moulins-Engilbert (2 pharmacies)
Pharmacie Pharmacie Pommier : 14 avis recuperes
Pharmacie Pharmacie Bougrier : 19 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[33/489] Commune : Mesvres (1 pharmacies)
Pharmacie Pharmacie Brisard : 9 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[34/489] Commune : Avoudrey (1 pharmacies)
Pharmacie Pharmacie : 12 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[35/489] Commune : Moissey (1 pharmacies)
Pharmacie Pharmacie Flamion : 17 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[36/489] Commune : Besançon (40 pharmacies)
  Sous-lot 1/2 (25 pharmacies)
Pharmacie Pharmacie FEIN : 31 avis recuperes
Pharmacie Pharmacie de Brégille : 22 avis recuperes
Pharmacie Pharmacie Moderne : 31 avis recuperes
Pharmacie Pharmacie Donard : 26 avis recuperes
Pharmacie Pharmacie de la Combe Saragosse : 24 avis recuperes
Pharmacie Pharmacie du Languedoc : 38 avis recuperes
Pharmacie Pharmacie Arnoux : 38 avis recuperes
Pharmacie Pharmacie Saint-Claude : 56 avis recuperes
Pharmacie Pharmacie du Théatre : 20 avis recuperes
Pharmacie Pharmacie de Palente : 235 avis recuperes
Pharmacie Pharmacie du Poylgone : 0 avis recuperes
Pharmacie Pharmacie Pasteur : 26 avis recuperes
Pharmacie Pharmacie Malot : 26 avis recuperes
Pharmacie Pharmacie des Epoisses : 16 avis recuperes
Pharmacie Pharmacie du Boulevard : 28 avis recuperes
Pharmacie Grande Pharmacie de la Citadelle : 83 avis recuperes
Pharmacie Pharmacie Fontaine Argent : 38 avis recuperes
Pharmacie Pharmacie Métayer : 20 avis recuperes
Pharmacie Pharmacie Lhosmot : 32 avis recuperes
Pharmacie Pharmacie Maphiba : 82 avis recuperes
Pharmacie Pharmacie de la Mouillère : 21 avis recuperes
Pharmacie Pharmacie Laalou : 31 avis recuperes
Pharmacie Pharmacie Chauvelot : 13 avis recuperes
Pharmacie Pharmacie Flore : 36 avis recuperes
Pharmacie Pharmacie des Tilleroyes : 537 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
  Sous-lot 2/2 (15 pharmacies)
Pharmacie Pharmacie de Battant : 57 avis recuperes
Pharmacie Pharmacie Mahut et Cie : 30 avis recuperes
Pharmacie Pharmacie Gillet : 39 avis recuperes
Pharmacie Pharmacie Gauthier Nicolas : 62 avis recuperes
Pharmacie Pharmacie Levillain : 22 avis recuperes
Pharmacie Pharmacie de Montrapon : 54 avis recuperes
Pharmacie Aprium Pharmacie : 33 avis recuperes
Pharmacie Pharmacie Comte : 74 avis recuperes
Pharmacie Pharmacie du Capitole : 15 avis recuperes
Pharmacie Pharmacie Dupont : 52 avis recuperes
Pharmacie Pharmacie du Parc : 28 avis recuperes
Pharmacie Pharmacie du Stade : 46 avis recuperes
Pharmacie Pharmacie des Buis : 46 avis recuperes
Pharmacie Pharmacie de Canot : 48 avis recuperes
Pharmacie Pharmacie Île de France : 185 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[37/489] Commune : Autun (5 pharmacies)
Pharmacie Pharmacie Wintz : 0 avis recuperes
Pharmacie Pharmacie de l'Arbalète : 0 avis recuperes
Pharmacie Pharmacie Laurent Montagne : 6 avis recuperes
Pharmacie Grande Pharmacie Bonaparte : 78 avis recuperes
Pharmacie Pharmacie de la Gare : 85 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[38/489] Commune : Tournus (3 pharmacies)
  Resultat suspect (10 avis) pour Pharmacie Veniat, nouvelle tentative...
Pharmacie Pharmacie des Recollets : 28 avis recuperes
Pharmacie Pharmacie Veniat : 10 avis recuperes
Pharmacie Pharmacie VEAU : 527 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[39/489] Commune : Is-sur-Tille (2 pharmacies)
Pharmacie Pharmacie des 3 Rivières : 20 avis recuperes
Pharmacie Pharmacie Barrière et Associés : 69 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[40/489] Commune : Charquemont (2 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Chapitaux Chambon : 27 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[41/489] Commune : Louhans-Châteaurenaud (5 pharmacies)
Pharmacie Amplifon Groupe France : 6 avis recuperes
Pharmacie Pharmacie Varlot : 12 avis recuperes
Pharmacie Pharmacie Bressane Pascal Nely : 24 avis recuperes
Pharmacie Pharmacie du Progrès : 27 avis recuperes
Pharmacie Pharmacie Saint-Jean : 35 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[42/489] Commune : Morre (1 pharmacies)
Pharmacie Pharmacie Avis : 3 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[43/489] Commune : Hérimoncourt (2 pharmacies)
Pharmacie Pharmacie Gasser : 16 avis recuperes
Pharmacie Pharmacie Schneller : 24 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[44/489] Commune : Paron (1 pharmacies)
Pharmacie Grande pharmacie de Paron : 69 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[45/489] Commune : Anost (1 pharmacies)
Pharmacie Pharmacie Topie : 7 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[46/489] Commune : Génelard (1 pharmacies)
Pharmacie Pharmacie du Bourg : 9 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[47/489] Commune : Aiserey (1 pharmacies)
Pharmacie Pharmacie des Tilleuls : 30 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[48/489] Commune : Pougues-les-Eaux (1 pharmacies)
Pharmacie Pharmacie de la Source : 22 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[49/489] Commune : Talant (4 pharmacies)
Pharmacie Pharmacie des Acacias : 21 avis recuperes
Pharmacie Pharmacie Herboristerie des Cerisiers : 22 avis recuperes
Pharmacie Pharmacie des Arandes : 20 avis recuperes
Pharmacie Pharmacie du Point du Jour : 48 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[50/489] Commune : Nuits-Saint-Georges (3 pharmacies)
Pharmacie Pharmacie Saint-Georges : 16 avis recuperes
Pharmacie Pharmacie Nicolas : 22 avis recuperes
Pharmacie Pharmacie Massot Perrad : 68 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[51/489] Commune : Champignelles (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[52/489] Commune : Baume-les-Dames (3 pharmacies)
  Resultat suspect (10 avis) pour Pharmacie Hergueux Simonin, nouvelle tentative...
Pharmacie Pharmacie Centrale : 23 avis recuperes
Pharmacie Pharmacie des Arcades : 14 avis recuperes
Pharmacie Pharmacie Hergueux Simonin : 10 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[53/489] Commune : Frasne (1 pharmacies)
Pharmacie Pharmacie des Droseras : 59 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[54/489] Commune : Les Hôpitaux-Neufs (1 pharmacies)
Pharmacie Pharmacie du Mont d'Or : 46 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[55/489] Commune : Lugny (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[56/489] Commune : Monéteau (2 pharmacies)
Pharmacie Pharmacie De La Poste : 37 avis recuperes
Pharmacie Pharmacie de l'Espérance : 110 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[57/489] Commune : Charnay-lès-Mâcon (2 pharmacies)
Pharmacie Pharmacie de la Coupée : 50 avis recuperes
Pharmacie Pharmacie Aprium Charnay : 72 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[58/489] Commune : Bavans (2 pharmacies)
Pharmacie Pharmacie Dubail : 5 avis recuperes
Pharmacie Pharmacie Benaim : 20 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[59/489] Commune : Laignes (1 pharmacies)
Pharmacie Pharmacie Vessie : 17 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[60/489] Commune : Toulon-sur-Arroux (1 pharmacies)
  Resultat suspect (10 avis) pour Pharmacie Pelmourges, nouvelle tentative...
Pharmacie Pharmacie Pelmourges : 10 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[61/489] Commune : Authume (1 pharmacies)
Pharmacie Pharmacie : 19 avis recuperes
Lot traite. Fichier sauvegarde : avis_bourgogne_franche_comte.csv
[62/489] Commune : Toucy (2 pharmacies)
Pharmacie Pharmacie Menard : 27 avis recuperes
Pharmacie Pharmacie de la Puisaye : 136 avis recuperes

In [62]:
df_region = pd.read_csv("pharmacies_par_region/pharmacies_bourgogne_franche_comte.csv", sep=";")
df_avis = pd.read_csv("avis_bourgogne_franche_comte.csv", sep=";", encoding="utf-8-sig")

total_pharmacies = df_region["result_label"].nunique()
compte_par_adresse = df_avis.groupby("adresse_pharmacie").size()
adresses_scrapees = set(compte_par_adresse.index)
nb_scrapees = len(adresses_scrapees)
nb_avec_0_avis = total_pharmacies - nb_scrapees
nb_avec_10_avis = (compte_par_adresse == 10).sum()

print("Total pharmacies :", total_pharmacies)
print(f"Pharmacies scrapees : {nb_scrapees} / {total_pharmacies}")
print("Pharmacies avec 0 avis :", nb_avec_0_avis)
print("Pharmacies avec 10 avis :", nb_avec_10_avis)

Total pharmacies : 952
Pharmacies scrapees : 849 / 952
Pharmacies avec 0 avis : 103
Pharmacies avec 10 avis : 12

## Region 3 : Centre-Val de Loire

In [64]:
await scraper_une_region(
    fichier_region="pharmacies_par_region/pharmacies_centre_val_de_loire.csv",
    fichier_sortie="avis_centre_val_de_loire.csv",
    nb_pages_parallele=4,
)

Region : pharmacies_par_region/pharmacies_centre_val_de_loire.csv
Nombre total de communes : 363
[1/363] Commune : Orléans (25 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Henri : 25 avis recuperes
Pharmacie Pharmacie des Blossières : 37 avis recuperes
Pharmacie Pharmacie Val de Loire : 82 avis recuperes
Pharmacie Pharmacie Bigarre : 47 avis recuperes
Pharmacie Pharmacie des Tourelles : 57 avis recuperes
Pharmacie Pharmacie de France : 74 avis recuperes
Pharmacie Pharmacie Fontvieille Marliere : 40 avis recuperes
Pharmacie Pharmacie Dunois : 77 avis recuperes
Pharmacie Pharmacie Émile Zola : 43 avis recuperes

Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed\nCall log:\n  - waiting for locator("div[data-review-id]").nth(406).locator(".wiI7pd").first\n')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed
Call log:
  - waiting for locator("div[data-review-id]").nth(406).locator(".wiI7pd").first

Pharmacie Pharmacie de la Nouvelle Orléans : 26 avis recuperes
Pharmacie Pharmacie Centrale : 147 avis recuperes
Pharmacie Pharmacie du Théâtre : 0 avis recuperes
Pharmacie Pharmacie Chaborel : 147 avis recuperes
Pharmacie Pharmacie de l'Argonne : 32 avis recuperes
Pharmacie Pharmacie de la Croix Morin (Lafayette) : 306 avis recuperes
Pharmacie Pharmacie de la Croix Fleury : 73 avis recuperes
Pharmacie Pharmacie Saint-Jean M Plateau : 53 avis recuperes
Pharmacie Pharmacie Gambetta : 46 avis recuperes
Pharmacie Pharmacie de la Poste : 57 avis recuperes
Pharmacie Pharmacie de la Bolière : 143 avis recuperes
Pharmacie Pharmacie de l'Indien : 104 avis recuperes
Pharmacie Pharmacie du Rond Point : 131 avis recuperes
Pharmacie Grande Pharmacie du Châtelet : 103 avis recuperes
Pharmacie Pharmacie de la Cigogne : 583 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[2/363] Commune : Bourges (21 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie de la Croix Blanche : 16 avis recuperes
Pharmacie Pharmacie Mabilleau : 21 avis recuperes
Pharmacie Pharmacie des Pijolins : 25 avis recuperes
Pharmacie Pharmacie de Turly : 57 avis recuperes
Pharmacie Pharmacie Jacques Cœur : 23 avis recuperes
Pharmacie Pharmacie Centrale : 37 avis recuperes
Pharmacie Pharmacie de la Gare : 42 avis recuperes
Pharmacie Pharmacie Mathieu : 50 avis recuperes
Pharmacie Pharmacie Fouassier : 27 avis recuperes
Pharmacie Pharmacie des Marronniers : 47 avis recuperes
Pharmacie Pharmacie de Paris : 64 avis recuperes
Pharmacie Pharmacie Brunet : 58 avis recuperes
Pharmacie Pharmacie d'Asnieres Danton : 66 avis recuperes
Pharmacie La Grande Pharmacie : 59 avis recuperes
Pharmacie Pharmacie Buchet : 84 avis recuperes
Pharmacie Pharmacie Baudens : 59 avis recuperes
Pharmacie Pharmacie du Prado : 62 avis recuperes
Pharmacie Pharmacie des Cordeliers : 35 avis recuperes
Pharmacie Pharmacie des Gibjoncs : 27 avis recuperes
Pharmacie Pharmacie du Val d'Auron : 48 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[3/363] Commune : Amilly (2 pharmacies)
  Resultat suspect (10 avis) pour Pharmacie du Pont Gaillard, nouvelle tentative...
Pharmacie Pharmacie du Pont Gaillard : 10 avis recuperes
Pharmacie Pharmacie Viroy Nivelle : 70 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[4/363] Commune : Saint-Cyr-sur-Loire (6 pharmacies)
2 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie du Charentais : 33 avis recuperes
Pharmacie Pharmacie des Maisons Blanches : 33 avis recuperes
Pharmacie Pharmacie Bertolino : 41 avis recuperes
Pharmacie Pharmacie Victor Hugo : 51 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[5/363] Commune : Vineuil (3 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Morin : 35 avis recuperes
Pharmacie Pharmacie Moreau : 70 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[6/363] Commune : Bléré (3 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Echegut : 38 avis recuperes
Pharmacie Pharmacie Bléroise : 72 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[7/363] Commune : Vendôme (9 pharmacies)
Pharmacie Pharmacie des Rottes : 30 avis recuperes
Pharmacie Pharmacie Segura : 30 avis recuperes
Pharmacie Pharmacie Gerbier : 26 avis recuperes
Pharmacie Pharmacie du Faubourg : 40 avis recuperes
Pharmacie Pharmacie de la Madeleine : 9 avis recuperes
Pharmacie Pharmacie Segura : 30 avis recuperes
Pharmacie Pharmacie de l'Avenue : 51 avis recuperes
Pharmacie Pharmacie de la Pierre Levée : 25 avis recuperes
Pharmacie Pharmacie de Courtiras : 39 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[8/363] Commune : Bourgueil (2 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Morin : 49 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[9/363] Commune : Mardié (1 pharmacies)
Pharmacie Pharmacie les Oliviers : 56 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[10/363] Commune : Azay-sur-Cher (1 pharmacies)
Pharmacie Pharmacie du Cher : 28 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[11/363] Commune : Issoudun (6 pharmacies)
Pharmacie Pharmacie Clerget Delphine : 17 avis recuperes
Pharmacie Pharmacie Viano-Joffre : 41 avis recuperes
Pharmacie Pharmacie Peyroux : 63 avis recuperes
Pharmacie Pharmacie de Bel Air : 35 avis recuperes
Pharmacie Pharmacie Jolivet Jean-Gabriel : 45 avis recuperes
Pharmacie Pharmacie Centrale : 41 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[12/363] Commune : Saint-Jean-de-Braye (5 pharmacies)
Pharmacie Pharmasie Abraysienne : 0 avis recuperes
Pharmacie Pharmacie des Longues Allées : 44 avis recuperes
Pharmacie Pharmacie de la Mairie : 78 avis recuperes
Pharmacie Pharmacie Du Centre : 94 avis recuperes
Pharmacie Pharmacie Saint Loup : 77 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[13/363] Commune : Soings-en-Sologne (1 pharmacies)
Pharmacie Pharmacie Trestard : 6 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[14/363] Commune : Genillé (1 pharmacies)
Pharmacie Pharmacie Burrillon : 32 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[15/363] Commune : Richelieu (2 pharmacies)
Pharmacie Pharmacie du Marché : 15 avis recuperes
Pharmacie Pharmacie Auger-Barre : 15 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[16/363] Commune : Mont-près-Chambord (1 pharmacies)
Pharmacie Pharmacie de Mont : 46 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[17/363] Commune : Reugny (1 pharmacies)
Pharmacie Pharmacie de la Brenne : 26 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[18/363] Commune : Tournon-Saint-Martin (1 pharmacies)
Pharmacie Pharmacie Multon : 17 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[19/363] Commune : Joué-lès-Tours (12 pharmacies)
Pharmacie Pharmacie de l'Étoile : 47 avis recuperes
Pharmacie Pharmacie de la Rabiere : 30 avis recuperes
Pharmacie Pharmacie de la Vallée Violette : 67 avis recuperes
Pharmacie Pharmacie Chantepie : 91 avis recuperes
Pharmacie Pharmacie de l'Épend : 33 avis recuperes
Pharmacie Pharmacie de l'Alouette : 28 avis recuperes
Pharmacie Pharmacie Chantepie : 91 avis recuperes
Pharmacie Pharmacie Centrale : 107 avis recuperes
Pharmacie Pharmacie de l'Ilot : 29 avis recuperes
Pharmacie Pharmacie La Jocondie : 17 avis recuperes
Pharmacie Pharmacie mutualiste : 83 avis recuperes
Pharmacie Pharmacie Lavoisier : 40 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[20/363] Commune : Saint-Gervais-la-Forêt (1 pharmacies)
Pharmacie Pharmacie Lefèvre : 122 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[21/363] Commune : Tours (49 pharmacies)
  Sous-lot 1/2 (25 pharmacies)
2 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Lamartine : 22 avis recuperes
Pharmacie Pharmacie de l'Avenue : 37 avis recuperes
Pharmacie Pharmacie d'Entraigues : 42 avis recuperes
Pharmacie Pharmacie des Trois Potions : 94 avis recuperes
Pharmacie Pharmacie Cœur de Loire : 45 avis recuperes
Pharmacie Pharmacie Briand-Bettler : 13 avis recuperes
Pharmacie Pharmacie du Parc : 36 avis recuperes
Pharmacie Pharmacie Des Tourettes : 76 avis recuperes
Pharmacie Pharmacie des Fontaines : 62 avis recuperes
Pharmacie Pharmacie du Progrès : 0 avis recuperes
Pharmacie Pharmacie des 2 Lions : 159 avis recuperes
Pharmacie Pharmacie des Fontaines : 62 avis recuperes
Pharmacie Pharmacie Mutualiste Tours Centre : 51 avis recuperes
Pharmacie Pharmacie du Centre : 59 avis recuperes
Pharmacie Pharmacie Delvallée : 28 avis recuperes
Pharmacie Pharmacie du Théâtre : 24 avis recuperes
Pharmacie Pharmacie Vinci : 67 avis recuperes
Pharmacie Pharmacie Maginot : 101 avis recuperes
Pharmacie Pharmacie Porte de Loire : 88 avis recuperes
Pharmacie Pharmacie Normale : 51 avis recuperes
Pharmacie Pharmacie Monconseil : 81 avis recuperes
Pharmacie Pharmacie principale : 237 avis recuperes
Pharmacie Pharmacie Velpeau : 41 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
  Sous-lot 2/2 (24 pharmacies)
Pharmacie Pharmacie Billot-Gauthier : 12 avis recuperes
Pharmacie Pharmacie du Maine : 86 avis recuperes
Pharmacie Pharmacie du Beffroi : 97 avis recuperes
Pharmacie Pharmacie de l'Horloge : 20 avis recuperes
Pharmacie Pharmacie Mirabeau : 96 avis recuperes
Pharmacie Pharmacie Saint-Éloi : 59 avis recuperes
Pharmacie Pharmacie des Halles : 21 avis recuperes
Pharmacie Pharmacie Beaujardin : 28 avis recuperes
Pharmacie Pharmacie Boussineq : 0 avis recuperes
Pharmacie Pharmacie du Grand Marché : 278 avis recuperes
Pharmacie Pharmacie Giraudeau : 41 avis recuperes
Pharmacie Pharmavie : 18 avis recuperes
Pharmacie Pharmacie de Montjoyeux : 24 avis recuperes
Pharmacie Pharmacie Mutualiste : 138 avis recuperes
Pharmacie Pharmacie Hogreul : 84 avis recuperes
Pharmacie Pharmacie Chauvin : 99 avis recuperes
Pharmacie Pharmacie des Rives du Cher : 31 avis recuperes
Pharmacie Pharmacie Tonnellé : 28 avis recuperes
Pharmacie Pharmacie du Sanitas : 34 avis recuperes
Pharmacie Pharmacie Paillhou : 38 avis recuperes
Pharmacie Pharmacie de la gare : 50 avis recuperes
Pharmacie Pharmacie Mery : 7 avis recuperes
Pharmacie Pharmacie Gomez : 35 avis recuperes
Pharmacie Pharmacie des Trois Rivières : 141 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[22/363] Commune : Semoy (1 pharmacies)
Pharmacie Mery : 78 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[23/363] Commune : Montargis (6 pharmacies)
Pharmacie Pharmacie des Lauriers : 16 avis recuperes
Pharmacie Pharmacie du Marché : 22 avis recuperes
Pharmacie Pharmacie Masson : 22 avis recuperes
  Resultat suspect (10 avis) pour Pharmacie Diaine Philizot, nouvelle tentative...
Pharmacie Pharmacie Dorée : 36 avis recuperes
Pharmacie Pharmacie de la Chaussée : 277 avis recuperes
Pharmacie Pharmacie Diaine Philizot : 10 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[24/363] Commune : Châtillon-Coligny (2 pharmacies)
Pharmacie Pharmacie Cassar : 0 avis recuperes
Pharmacie Pharmacie de Châtillon-Coligny : 60 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[25/363] Commune : Châteauroux (14 pharmacies)
Pharmacie Pharmacie Denanot Leyldé : 16 avis recuperes
Pharmacie Pharmacie Laleuf Daguet Christine : 37 avis recuperes
Pharmacie Pharmacie Equinoxe : 26 avis recuperes
Pharmacie Pharmacie Gambetta : 45 avis recuperes
Pharmacie Pharmacie Cazala : 82 avis recuperes
Pharmacie Pharmacie Mouchet : 44 avis recuperes
Pharmacie Pharmacie Quatresous Michel : 18 avis recuperes
Pharmacie Pharmacie Bernardeau : 53 avis recuperes
Pharmacie Pharmacie Saint-Jacques : 20 avis recuperes
Pharmacie Pharmacie Beaulieu : 25 avis recuperes
Pharmacie Pharmacie des Marins : 39 avis recuperes
Pharmacie Pharmacie Gobert Hélène et Vernédal Nicole : 50 avis recuperes
Pharmacie Pharmacie Simon-Bernardet : 21 avis recuperes
Pharmacie Pharmacie Bougeon-Cochet Marie-Hélène : 40 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[26/363] Commune : La Riche (4 pharmacies)
Pharmacie Pharmacie de la Mairie : 34 avis recuperes
Pharmacie Pharmacie du Prieuré : 30 avis recuperes
Pharmacie Pharmacie Bourgine : 54 avis recuperes
Pharmacie Pharmacie Saint-Anne : 69 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[27/363] Commune : Chécy (4 pharmacies)
  Resultat suspect (10 avis) pour Pharmacie Fournier, nouvelle tentative...
Pharmacie E.Leclerc Parapharmacie : 54 avis recuperes
Pharmacie Pharmacie Fournier : 10 avis recuperes
Pharmacie Pharmacie de Chécy : 83 avis recuperes
Pharmacie Pharmacie Chécy Belles Rives : 134 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[28/363] Commune : Thésée (1 pharmacies)
Pharmacie Pharmacie de Thésée : 25 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[29/363] Commune : Fondettes (4 pharmacies)
Pharmacie Pharmacie de la Poste : 0 avis recuperes
Pharmacie Pharmacie Halabi : 16 avis recuperes
Pharmacie Pharmacie des Hautes Roches : 58 avis recuperes
Pharmacie Pharmacie La Forge : 102 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[30/363] Commune : Theillay (1 pharmacies)
Pharmacie Pharmacie Principale : 24 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[31/363] Commune : Pontlevoy (2 pharmacies)
2 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[32/363] Commune : Saint-Avertin (5 pharmacies)
Pharmacie Pharmacie du Petit Cher : 12 avis recuperes
Pharmacie Pharmacien Giphar : 20 avis recuperes
Pharmacie Pharmacie des Pierres Plates : 45 avis recuperes
  Resultat suspect (10 avis) pour Pharmacie de l'Avenir, nouvelle tentative...
Pharmacie Pharmacie des Grands Champs : 57 avis recuperes
Pharmacie Pharmacie de l'Avenir : 10 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[33/363] Commune : Vierzon (10 pharmacies)
Pharmacie Pharmacie Nouvelle : 28 avis recuperes
Pharmacie Pharmacie de l'Avenue : 22 avis recuperes
Pharmacie Pharmacie Saint-Martin : 27 avis recuperes
Pharmacie Pharmacie du Forum : 74 avis recuperes
Pharmacie Pharmacie du Beffroi : 18 avis recuperes
  Resultat suspect (10 avis) pour Pharmacie Ben Aicha, nouvelle tentative...
Pharmacie Pharmacie de Puits Berteau : 51 avis recuperes
Pharmacie Pharmacie Ben Aicha : 10 avis recuperes
Pharmacie Pharmacie Bouillon : 33 avis recuperes
Pharmacie Pharmacie des Forges : 16 avis recuperes
Pharmacie Pharmacie de Chaillot : 53 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[34/363] Commune : Le Controis-en-Sologne (4 pharmacies)
Pharmacie Pharmacie du Château : 8 avis recuperes
Pharmacie Pharmacie du Centre : 23 avis recuperes
Pharmacie Pharmacie Veux : 130 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[35/363] Commune : Veigné (2 pharmacies)
Pharmacie Pharmacie Brion : 25 avis recuperes
Pharmacie Pharmacie Du Bourg : 33 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[36/363] Commune : Saint-Prest (1 pharmacies)
Pharmacie Pharmacie Siabas : 56 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[37/363] Commune : Saint-Flovier (1 pharmacies)
Pharmacie Pharmacie Bruneau Bigot Annick : 6 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[38/363] Commune : Clion (1 pharmacies)
Pharmacie Pharmacie de Clion : 16 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[39/363] Commune : Fleury-les-Aubrais (9 pharmacies)
Pharmacie Pharmacie Denizot : 15 avis recuperes
Pharmacie Pharmacie Guiberteau Rousselet : 47 avis recuperes
Pharmacie Pharmacie De Moras-Hervouet : 81 avis recuperes
Pharmacie Pharmacie Santoire : 42 avis recuperes
Pharmacie Pharmacie Fleuryssoise : 212 avis recuperes
Pharmacie Pharmacie Condorcet : 33 avis recuperes
Pharmacie E.Leclerc Parapharmacie : 63 avis recuperes
Pharmacie Pharmacie de Lignerolles : 20 avis recuperes
Pharmacie Pharmacie Jean Jaurès : 23 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[40/363] Commune : Ligny-le-Ribault (1 pharmacies)
Pharmacie Pharmacie Dudal : 13 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[41/363] Commune : Huisseau-sur-Mauves (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[42/363] Commune : Brou (3 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
  Resultat suspect (10 avis) pour Pharmacie de la Matrassière, nouvelle tentative...
Pharmacie Pharmacie de la Matrassière : 10 avis recuperes
Pharmacie Pharmacie des Acacias : 73 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[43/363] Commune : Villemandeur (2 pharmacies)
Pharmacie Pharmacie de l'Église : 48 avis recuperes
Pharmacie Pharmacie Bonnici : 49 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[44/363] Commune : Mer (2 pharmacies)
Pharmacie Pharmacie Centrale : 73 avis recuperes
Pharmacie Pharmacie HUET : 15 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[45/363] Commune : Baugy (1 pharmacies)
Pharmacie Pharmacie de la Halle : 25 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[46/363] Commune : Vailly-sur-Sauldre (1 pharmacies)
Pharmacie Pharmacie Chopineau : 20 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[47/363] Commune : La Chaussée-Saint-Victor (2 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie de l'Hermitage : 44 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[48/363] Commune : Briare (3 pharmacies)
Pharmacie Proxipharma : 13 avis recuperes
Pharmacie Pharmacie Rousseau : 48 avis recuperes
Pharmacie Pharmacie Levesque : 48 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[49/363] Commune : Gien (4 pharmacies)
Pharmacie Pharmacie du Pont : 65 avis recuperes
Pharmacie Pharmacie des Écoles : 65 avis recuperes
Pharmacie Pharmacie des Hauts de Gien : 38 avis recuperes
Pharmacie Pharmacie de la Loire : 228 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[50/363] Commune : Saint-Martin-d'Abbat (1 pharmacies)
Pharmacie Pharmacie Bureau Garenton : 49 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[51/363] Commune : Olivet (5 pharmacies)
Pharmacie Pharmacie du Loiret : 41 avis recuperes
Pharmacie Pharmacie d'Artois : 68 avis recuperes
Pharmacie Pharmacie Centrale : 67 avis recuperes
Pharmacie Pharmacie de l'Église : 31 avis recuperes
Pharmacie Pharmacie Septfonds : 165 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[52/363] Commune : Montrichard Val de Cher (3 pharmacies)
Pharmacie Pharmacie Giphar : 24 avis recuperes
Pharmacie Pharmacie du Donjon : 21 avis recuperes
Pharmacie Pharmacie des Arcades : 29 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[53/363] Commune : Châtillon-sur-Indre (2 pharmacies)
Pharmacie Pharmacie du Centre : 9 avis recuperes
Pharmacie Pharmacie du Donjon : 41 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[54/363] Commune : Mehun-sur-Yèvre (3 pharmacies)
Pharmacie Pharmacie Saint-Syph : 23 avis recuperes
Pharmacie Pharmacie de l'Horloge : 23 avis recuperes
Pharmacie Pharmacie Rousseau Guiné : 56 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[55/363] Commune : Saint-Jean-le-Blanc (3 pharmacies)
Pharmacie Pharmacie de la Fontaine : 28 avis recuperes
Pharmacie Pharmacie du Clos de l'Arche : 51 avis recuperes
Pharmacie Pharmacie Charpentier : 37 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[56/363] Commune : Bonneval (2 pharmacies)
Pharmacie Pharmacie TIBURCE : 50 avis recuperes
Pharmacie Pharmacie CALLENS : 61 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[57/363] Commune : Pezou (1 pharmacies)
Pharmacie Pharmacie Hermelin-Laurentie : 12 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[58/363] Commune : Charenton-du-Cher (1 pharmacies)
Pharmacie pharmacie de charenton : 14 avis recuperes
Lot traite. Fichier sauvegarde : avis_centre_val_de_loire.csv
[59/363] Commune : Aubigny-sur-Nère (2 pharmacies)

In [65]:
df_region = pd.read_csv("pharmacies_par_region/pharmacies_centre_val_de_loire.csv", sep=";")
df_avis = pd.read_csv("avis_centre_val_de_loire.csv", sep=";", encoding="utf-8-sig")

total_pharmacies = df_region["result_label"].nunique()
compte_par_adresse = df_avis.groupby("adresse_pharmacie").size()
adresses_scrapees = set(compte_par_adresse.index)
nb_scrapees = len(adresses_scrapees)
nb_avec_0_avis = total_pharmacies - nb_scrapees
nb_avec_10_avis = (compte_par_adresse == 10).sum()

print("Total pharmacies :", total_pharmacies)
print(f"Pharmacies scrapees : {nb_scrapees} / {total_pharmacies}")
print("Pharmacies avec 0 avis :", nb_avec_0_avis)
print("Pharmacies avec exactement 10 avis :", nb_avec_10_avis)

Total pharmacies : 698
Pharmacies scrapees : 599 / 698
Pharmacies avec 0 avis : 99
Pharmacies avec exactement 10 avis : 9

## Region 4 : Bretagne

In [54]:
await scraper_une_region(
    fichier_region="pharmacies_par_region/pharmacies_bretagne.csv",
    fichier_sortie="avis_bretagne.csv",
    nb_pages_parallele=5,
)

Region : pharmacies_par_region/pharmacies_bretagne.csv
Nombre total de communes : 493
[1/493] Commune : Séné (3 pharmacies)
Pharmacie Pharmacie des Voiles Rouges : 28 avis recuperes
Pharmacie Pharmacie Latouche : 29 avis recuperes
Pharmacie Pharmacie du Poulfanc : 98 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[2/493] Commune : Hennebont (5 pharmacies)
Pharmacie Pharmacie des ramparts : 0 avis recuperes
Pharmacie Pharmacie de la Maison Rouge : 17 avis recuperes
Pharmacie Pharmacie Le Ray - Manceron : 26 avis recuperes
Pharmacie Pharmacie Kergroix : 37 avis recuperes
Pharmacie Pharmacie de la Gardeloupe : 69 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[3/493] Commune : Saint-Jacques-de-la-Lande (4 pharmacies)
Pharmacie Pharmacie de la Croix Verte : 24 avis recuperes
Pharmacie Pharmacie Redondo : 29 avis recuperes
Pharmacie Pharmacie Saint-Jacques : 31 avis recuperes
Pharmacie Pharmacie Morinais : 115 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[4/493] Commune : Sarzeau (3 pharmacies)
Pharmacie Pharmacie des Trinitaires : 54 avis recuperes
Pharmacie Pharmacie du Golfe : 57 avis recuperes
Pharmacie Pharmacie de Rhuys : 55 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[5/493] Commune : Saint-Brieuc (12 pharmacies)
Pharmacie Pharmacie Videment : 48 avis recuperes
Pharmacie Pharmacie d'Armor : 55 avis recuperes
Pharmacie Pharmacie Le Gall : 22 avis recuperes
Pharmacie Pharmacie Saint-Pierre : 29 avis recuperes
Pharmacie Pharmacie Saint-Yves : 37 avis recuperes

Future exception was never retrieved
future: <Future finished exception=TargetClosedError('Target page, context or browser has been closed')>
playwright._impl._errors.TargetClosedError: Target page, context or browser has been closed

Pharmacie Pharmacie de l'Espace Saint-Lambert : 55 avis recuperes
Pharmacie Pharmacie Balzac : 35 avis recuperes
Pharmacie Pharmacie de Gouédic : 59 avis recuperes
Pharmacie Pharmacie Léonard de Vinci : 91 avis recuperes
Pharmacie Pharmacie de l'Université : 49 avis recuperes
Pharmacie Pharmacie des villages : 118 avis recuperes
Pharmacie Pharmacie de Robien : 34 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[6/493] Commune : Moëlan-sur-Mer (3 pharmacies)
  Resultat suspect (10 avis) pour Pharmacie Chardevel et Lecoq, nouvelle tentative...
Pharmacie Pharmacie du Centre : 26 avis recuperes
Pharmacie Pharmacie Principale : 26 avis recuperes
Pharmacie Pharmacie Chardevel et Lecoq : 10 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[7/493] Commune : Taupont (1 pharmacies)
Pharmacie Pharmacie LEGAVRE : 17 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[8/493] Commune : Quéven (2 pharmacies)
Pharmacie Pharmacie Charnal : 29 avis recuperes
Pharmacie La Pharmacie Verte : 20 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[9/493] Commune : Fougères (8 pharmacies)
Pharmacie Pharmacie des Orières : 29 avis recuperes
Pharmacie Pharmacie de la Poste : 26 avis recuperes
Pharmacie Pharmacie des Cotterets : 8 avis recuperes
Pharmacie Pharmacie de la Verrerie : 41 avis recuperes
Pharmacie Pharmacie de l'Europe : 52 avis recuperes
Pharmacie Pharmacie de la Douve : 69 avis recuperes
Pharmacie Pharmacie de Bonabry : 35 avis recuperes
Pharmacie Pharmacie du Croissant : 40 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[10/493] Commune : Broons (2 pharmacies)
Pharmacie Pharmacie Duguesclin : 29 avis recuperes
Pharmacie Pharmacie du Chalet : 25 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[11/493] Commune : Rennes (58 pharmacies)
  Sous-lot 1/3 (25 pharmacies)
Pharmacie Pharmacie du Pont de Nantes : 46 avis recuperes
Pharmacie Pharmacie du Progrès : 84 avis recuperes
Pharmacie Pharmacie Saint Cyr : 68 avis recuperes
Pharmacie Pharmacie Pascal : 73 avis recuperes
Pharmacie Pharmacie de la Binquenais : 37 avis recuperes
Pharmacie Pharmacie Salmon : 28 avis recuperes
Pharmacie Pharmacie des Longs Champs : 126 avis recuperes
Pharmacie Pharmacie de Nemours : 72 avis recuperes
Pharmacie Pharmacie Beauregard : 59 avis recuperes
Pharmacie Pharmacie des Gayeulles : 55 avis recuperes
Pharmacie Pharmacie de Villejean : 95 avis recuperes
Pharmacie Pharmacie Mabilais : 44 avis recuperes
Pharmacie Pharmacie de la Vilaine : 70 avis recuperes
Pharmacie Aprium Pharmacie du Blosne : 47 avis recuperes
Pharmacie Pharmacie Clemenceau : 39 avis recuperes
Pharmacie Pharmacie Rochard : 26 avis recuperes
Pharmacie Pharmacie Sarah Bernhardt : 72 avis recuperes
Pharmacie Pharmacie Colombia : 240 avis recuperes
Pharmacie Pharmacie de la Courrouze : 59 avis recuperes
Pharmacie Pharmacie du Gros Chêne : 46 avis recuperes
Pharmacie Pharmacie Grand Quartier : 147 avis recuperes
Pharmacie Pharmacie Notre-Dame : 39 avis recuperes
Pharmacie Pharmacie du Landry : 43 avis recuperes
Pharmacie Pharmacie St Germain : 33 avis recuperes
Pharmacie Pharmacie du Mail : 65 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
  Sous-lot 2/3 (25 pharmacies)
Pharmacie Pharmacie des Horizons : 20 avis recuperes
Pharmacie Pharmacie Oberthur : 31 avis recuperes
Pharmacie Pharmacie des Lices : 46 avis recuperes
Pharmacie Pharmacie de Bretagne : 78 avis recuperes
Pharmacie Pharmacie du Petit Baud : 41 avis recuperes
Pharmacie Pharmacie de l'Hôtel Dieu : 35 avis recuperes
Pharmacie Pharmacie Métro Jacques Cartier : 55 avis recuperes
Pharmacie Pharmacie de la Croix Carrée : 21 avis recuperes
Pharmacie Pharmacie Nguyen : 52 avis recuperes
Pharmacie Pharmacie Saint-Martin : 37 avis recuperes
Pharmacie Pharmacie du Cormier : 44 avis recuperes
Pharmacie Pharmacie Pont de Châteaudun : 42 avis recuperes
Pharmacie Grande Pharmacie de Rennes : 345 avis recuperes
Pharmacie Pharmacie Léon Bourgeois : 62 avis recuperes
Pharmacie Pharmacie de Bréquigny : 40 avis recuperes
Pharmacie Pharmacie du Chapitre : 52 avis recuperes
Pharmacie Pharmacie Kerangal : 41 avis recuperes
Pharmacie Pharmacie des Almadies : 27 avis recuperes
Pharmacie Pharmacie de la Bellangerais : 33 avis recuperes
Pharmacie Pharmacie Liberté : 50 avis recuperes
Pharmacie Pharmacie Cleunay : 65 avis recuperes
Pharmacie Pharmacie Saint-Hélier : 87 avis recuperes
Pharmacie Pharmacie de Bel Air : 26 avis recuperes
Pharmacie Pharmacie du Verger : 30 avis recuperes
Pharmacie Pharmacie de Maurepas : 45 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
  Sous-lot 3/3 (8 pharmacies)
Pharmacie Pharmacie de la Poterie : 26 avis recuperes
Pharmacie Pharmacie Bigot-Labbe : 24 avis recuperes
Pharmacie Pharmacie République : 49 avis recuperes
Pharmacie Pharmacie Churchill : 52 avis recuperes
Pharmacie Pharmacie Anatole France : 72 avis recuperes
Pharmacie Pharmacie Anne Ferec : 45 avis recuperes
Pharmacie Pharmacie de la Madeleine : 40 avis recuperes
Pharmacie Pharmacie du Centre Alma : 169 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[12/493] Commune : Bruz (6 pharmacies)
Pharmacie Pharmacie Mercier : 15 avis recuperes
Pharmacie Pharmacie Rousseau : 27 avis recuperes
Pharmacie Pharmacie de Bretagne : 25 avis recuperes
Pharmacie Pharmacie Du Vert Buisson : 45 avis recuperes
Pharmacie Pharmacie Macher-Talibart : 31 avis recuperes
Pharmacie Pharmacie Bertrand-Riou : 20 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[13/493] Commune : Châtelaudren-Plouagat (1 pharmacies)
Pharmacie Pharmacie du Châté : 27 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[14/493] Commune : Lorient (22 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Herzog Vincendeau : 0 avis recuperes
Pharmacie Pharmacie de Keryado : 0 avis recuperes
Pharmacie Pharmacie de Monistrol : 0 avis recuperes
Pharmacie Gérant Pharmacie de Monistrol Lorient : 0 avis recuperes
Pharmacie Pharmacie de Merville : 24 avis recuperes
Pharmacie Pharmacie de Kerentrech : 32 avis recuperes
Pharmacie Pharmacie Mutualiste : 21 avis recuperes
Pharmacie Pharmacie de Saint-Armel : 31 avis recuperes
Pharmacie Pharmacie Victoria : 22 avis recuperes
Pharmacie Pharmacie du Ter : 19 avis recuperes
Pharmacie Pharmacie de Kerfichant : 70 avis recuperes
Pharmacie Pharmacie la Liberté : 50 avis recuperes
Pharmacie Pharmacie Kervénanec : 24 avis recuperes
Pharmacie Pharmacie d'Arvor : 1 avis recuperes
Pharmacie Pharmacie Nicol : 27 avis recuperes
Pharmacie Pharmacie du Centre : 5 avis recuperes
Pharmacie Pharmacie K2 : 93 avis recuperes
Pharmacie Pharmacie Le Roch : 14 avis recuperes
Pharmacie Pharmacie Jahier Billoir : 31 avis recuperes
Pharmacie Pharmacie Laudrain : 30 avis recuperes
Pharmacie Pharmacie de la Gare : 114 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[15/493] Commune : Auray (6 pharmacies)
Pharmacie Pharmacie des Halles : 0 avis recuperes
Pharmacie Pharmacie Porte Océane : 0 avis recuperes
Pharmacie Pharmacie Centrale : 0 avis recuperes
Pharmacie Pharmacie Bellouard : 0 avis recuperes
Pharmacie Pharmacie Morvan : 57 avis recuperes
Pharmacie Pharmacie d'Arvor : 106 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[16/493] Commune : Sizun (2 pharmacies)
Pharmacie Pharmacie Humbert : 26 avis recuperes
Pharmacie Pharmacie de Sizun : 26 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[17/493] Commune : Pordic (2 pharmacies)
Pharmacie Pharmacie de l'Ic : 45 avis recuperes
Pharmacie Pharmacie du Littoral : 44 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[18/493] Commune : Pont-Aven (1 pharmacies)
Pharmacie Pharmacie du Bois d'Amour : 25 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[19/493] Commune : Servon-sur-Vilaine (1 pharmacies)
Pharmacie Pharmacie du Gué : 17 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[20/493] Commune : Bourbriac (1 pharmacies)
Pharmacie Pharmacie du Pays Briacin : 34 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[21/493] Commune : Pont-Scorff (1 pharmacies)
Pharmacie PHARMACIE de Pont Scorff : 0 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[22/493] Commune : Brest (35 pharmacies)
  Sous-lot 1/2 (25 pharmacies)
Pharmacie Pharmacie de Kérinou : 0 avis recuperes
Pharmacie Chez ma Pharmacienne : 0 avis recuperes
Pharmacie Pharmacie Rocher et Le Roux : 0 avis recuperes
Pharmacie Pharmacie Le Graet : 29 avis recuperes
Pharmacie Pharmacie Centrale des Quatre Moulins : 29 avis recuperes
Pharmacie Pharmacie Saint-Laurent : 20 avis recuperes
Pharmacie Pharmacie Nicolas : 46 avis recuperes
Pharmacie Pharmacie Bazin : 40 avis recuperes
Pharmacie Pharmacie de l'Iroise : 166 avis recuperes
Pharmacie Pharmacie de Recouvrance : 54 avis recuperes
Pharmacie Pharmacie Conan : 104 avis recuperes
Pharmacie Pharmacie du Guelmeur : 24 avis recuperes
Pharmacie Pharmacie du Pont Neuf : 2 avis recuperes
Pharmacie Pharmacie du Serpent : 42 avis recuperes
Pharmacie Pharmacie Tea : 13 avis recuperes
Pharmacie Pharmacie des Arcades : 22 avis recuperes
Pharmacie Pharmacie des Halles : 37 avis recuperes
Pharmacie Pharmacie des Universités : 57 avis recuperes
Pharmacie Pharmacie des Voiles : 72 avis recuperes
Pharmacie Pharmacie : 69 avis recuperes
Pharmacie Pharmacie des 4 Moulins : 20 avis recuperes
Pharmacie Pharmacie Stéphan : 63 avis recuperes
Pharmacie Pharmacie Blanchard : 63 avis recuperes
Pharmacie Pharmacie Liberté : 67 avis recuperes
Pharmacie Pharmacie Chamarel : 34 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
  Sous-lot 2/2 (10 pharmacies)
Pharmacie Pharmacie Feys : 24 avis recuperes
Pharmacie Pharmacie Centrale : 45 avis recuperes
Pharmacie Pharmacie Ropars : 51 avis recuperes
Pharmacie Pharmacie de Saint-Marc : 54 avis recuperes
Pharmacie Pharmacie de l'Octroi : 48 avis recuperes
Pharmacie Pharmacie de Saint-Pierre : 51 avis recuperes
Pharmacie Pharmacie du Douric : 48 avis recuperes
Pharmacie Pharmacie de Bellevue : 82 avis recuperes
Pharmacie Pharmacie du Petit Paris : 58 avis recuperes
Pharmacie Lafayette : 79 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[23/493] Commune : Plourin-lès-Morlaix (2 pharmacies)
Pharmacie Pharmacie des Arcades : 13 avis recuperes
Pharmacie Pharmacie Kerboriou : 30 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[24/493] Commune : Châtillon-en-Vendelais (1 pharmacies)
Pharmacie Pharmacie du Vendelais : 8 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[25/493] Commune : Châteauneuf-du-Faou (1 pharmacies)
Pharmacie Pharmacie de Châteauneuf : 66 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[26/493] Commune : Plouray (1 pharmacies)
Pharmacie Pharmacie Baroan : 3 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[27/493] Commune : Plabennec (2 pharmacies)
Pharmacie Pharmacie Apprioual : 30 avis recuperes
Pharmacie Libéoz : 20 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[28/493] Commune : Plougasnou (2 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie de Poulbraou : 15 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[29/493] Commune : Saint-Gildas-de-Rhuys (1 pharmacies)
Pharmacie Pharmacie Cornier : 39 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[30/493] Commune : Rochefort-en-Terre (1 pharmacies)
Pharmacie Pharmacie Paytra : 19 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[31/493] Commune : Évran (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[32/493] Commune : Saint-Thégonnec Loc-Eguiner (1 pharmacies)
Pharmacie Pharmacie Morin-Perini : 25 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[33/493] Commune : Ploemeur (7 pharmacies)
Pharmacie Pharmacie Pin : 11 avis recuperes
Pharmacie Pharmacie du Centre : 23 avis recuperes
Pharmacie Pharmacie Guily : 59 avis recuperes
Pharmacie Pharmacie de Kervam : 14 avis recuperes
Pharmacie Pharmacie Charlot : 28 avis recuperes
Pharmacie Pharmacie Delcroix : 38 avis recuperes
Pharmacie Pharmacie de l'Église : 22 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[34/493] Commune : Le Palais (1 pharmacies)
Pharmacie Pharmacie de la Citadelle : 59 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[35/493] Commune : Lannion (7 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Belloir : 1 avis recuperes
Pharmacie Pharmacie De Saint-Marc : 23 avis recuperes
Pharmacie Pharmacie Peron Courgeon : 38 avis recuperes
Pharmacie Pharmacie Gaboriaud : 53 avis recuperes
Pharmacie Pharmacie Kervarec-Tilly : 53 avis recuperes
Pharmacie Pharmacie Adam : 46 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[36/493] Commune : Péaule (1 pharmacies)
Pharmacie Pharmacie Palicot : 39 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[37/493] Commune : Quimper (23 pharmacies)
Pharmacie Pharmacie Saint-Mathieu : 12 avis recuperes
Pharmacie Pharmacie du Braden : 21 avis recuperes
Pharmacie Pharmacie de Lududu : 48 avis recuperes
Pharmacie Pharmacie de Cornouaille : 47 avis recuperes
Pharmacie Pharmacie Louzou Mad : 32 avis recuperes
Pharmacie La Pharmacie Bleue : 121 avis recuperes
Pharmacie Pharmacie Pennaneach : 24 avis recuperes
Pharmacie Pharmacie de Paris : 66 avis recuperes
Pharmacie Lafayette : 103 avis recuperes
Pharmacie Pharmacie Simon : 19 avis recuperes
Pharmacie Pharmacie de Kermoysan : 32 avis recuperes
Pharmacie Pharmacie Henaff Portais : 4 avis recuperes
Pharmacie Pharmacie de la Gare : 31 avis recuperes
Pharmacie Pharmacie Ty Bos : 36 avis recuperes
Pharmacie Pharmacie Saint-Laurent : 18 avis recuperes
Pharmacie Pharmacie d'Ergué Armel : 41 avis recuperes
Pharmacie Pharmacie du Moulin Vert : 32 avis recuperes
Pharmacie Pharmacie de La Fontaine : 20 avis recuperes
Pharmacie Pharmacie Pernès : 28 avis recuperes
Pharmacie Pharmacie Baudet : 25 avis recuperes
Pharmacie Pharmacie Lessard : 24 avis recuperes
Pharmacie Pharmacie de la Cathédrale : 51 avis recuperes
Pharmacie Pharmacie Breizh Izel : 262 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[38/493] Commune : Questembert (3 pharmacies)
Pharmacie Pharmacie Serandour-Blangonet : 31 avis recuperes
Pharmacie Pharmacie Hallegouet-Cobigo : 47 avis recuperes
Pharmacie Pharmacie des Arômes : 40 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[39/493] Commune : Plouvien (1 pharmacies)
Pharmacie Pharmacie de Plouvien : 35 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[40/493] Commune : Saint-Avé (5 pharmacies)
Pharmacie Pharmacie du Centre : 21 avis recuperes
Pharmacie Pharmacie de la Croix Verte : 21 avis recuperes
Pharmacie Pharmacie de Bossuet : 24 avis recuperes
Pharmacie Pharmacie des Trois Rois : 52 avis recuperes
Pharmacie Pharmacie du loc : 65 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[41/493] Commune : Douarnenez (7 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Jumel : 18 avis recuperes
Pharmacie Pharmacie Bobinet : 17 avis recuperes
Pharmacie Pharmacie de l'Yser : 19 avis recuperes
Pharmacie Pharmacie Leadersanté : 19 avis recuperes
Pharmacie Pharmacie Roussot : 33 avis recuperes
Pharmacie Pharmacie Bolomig : 17 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[42/493] Commune : Concarneau (10 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Les Filets Bleus : 4 avis recuperes
Pharmacie Pharmacie du Passage : 20 avis recuperes
Pharmacie Pharmacie des Halles : 22 avis recuperes
Pharmacie Pharmacie de Lanriec : 52 avis recuperes
Pharmacie Pharmacie Jaouen - Guyomard : 37 avis recuperes
Pharmacie Pharmacie Michelet : 35 avis recuperes
Pharmacie Pharmacie Huette-Moncelet : 56 avis recuperes
Pharmacie Pharmacie Quai Carnot : 56 avis recuperes
Pharmacie Pharmacie de la Baie : 73 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[43/493] Commune : Belz (1 pharmacies)
Pharmacie Véronique Barillon : 0 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[44/493] Commune : Plouzané (4 pharmacies)
Pharmacie Pharmacie Maherilaza - Leroy : 2 avis recuperes
Pharmacie Pharmacie de Castel Nevez : 17 avis recuperes
Pharmacie Pharmacie de la Trinité : 54 avis recuperes
Pharmacie Pharmacie de Coutures et Diebold : 38 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[45/493] Commune : Montauban-de-Bretagne (2 pharmacies)
Pharmacie Pharmacie du Centre : 33 avis recuperes
Pharmacie Pharmacie de Brocéliande : 75 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[46/493] Commune : Dol-de-Bretagne (2 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Rehel : 123 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[47/493] Commune : Montreuil-sur-Ille (1 pharmacies)
Pharmacie Pharmacie Schneegans : 34 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[48/493] Commune : Landerneau (6 pharmacies)
Pharmacie Pharmacie Centrale : 37 avis recuperes
Pharmacie Pharmacie Lacoste : 128 avis recuperes
Pharmacie Pharmacie Jouillat Dutreix : 45 avis recuperes
Pharmacie Pharmacie de la Gare : 55 avis recuperes
Pharmacie Pharmacie Bernicot : 72 avis recuperes
Pharmacie Pharmacie Premel-Cabic-Pihuit : 14 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[49/493] Commune : Le Relecq-Kerhuon (4 pharmacies)
Pharmacie Pharmacie Potin : 20 avis recuperes
Pharmacie Pharmacie Martin : 16 avis recuperes
Pharmacie Pharmacie de l'Église : 58 avis recuperes
Pharmacie Pharmacie du Moulin Blanc : 55 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[50/493] Commune : Saint-Malo (20 pharmacies)
Pharmacie Pharmacie de Rochebonne : 18 avis recuperes
Pharmacie Pharmacie des Fontenelles : 28 avis recuperes
Pharmacie Pharmacie de l'Espérance : 64 avis recuperes
Pharmacie Pharmacie Centrale Servannaise : 33 avis recuperes
Pharmacie Pharmacie de Rothéneuf : 15 avis recuperes
Pharmacie Pharmacie du Centre Commercial La Découverte : 43 avis recuperes
Pharmacie Pharmacie de la Croix Desilles : 95 avis recuperes
Pharmacie Pharmacie de la Roulais : 18 avis recuperes
Pharmacie Pharmacie du Théâtre : 55 avis recuperes
Pharmacie Pharmacie des Thermes : 48 avis recuperes
Pharmacie Pharmacie de Rocabey : 35 avis recuperes
Pharmacie Pharmacie Intra-muros : 63 avis recuperes
Pharmacie Pharmacie du Mouchoir Vert : 52 avis recuperes
Pharmacie Pharmacie Danibert-Vautier : 24 avis recuperes
Pharmacie Pharmacie Quernec : 32 avis recuperes
Pharmacie Pharmacie des Corsaires : 43 avis recuperes
Pharmacie Pharmacie de la Gare : 263 avis recuperes
Pharmacie Lafayette : 161 avis recuperes
Pharmacie Pharmacie Bellevue : 34 avis recuperes
Pharmacie Pharmacie Evain Delisle : 56 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[51/493] Commune : Lamballe-Armor (6 pharmacies)
Pharmacie Pharmacie du Marché : 15 avis recuperes
Pharmacie Pharmacie du Chalet : 20 avis recuperes
Pharmacie Pharmacie du Liffré : 33 avis recuperes
Pharmacie Pharmacie du Colombier : 21 avis recuperes
Pharmacie Pharmacie du Val d'Armor : 44 avis recuperes
Pharmacie Pharmacie de St Martin : 56 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[52/493] Commune : Tréguier (2 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie des Quais : 73 avis recuperes
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[53/493] Commune : Saint-Erblon (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_bretagne.csv
[54/493] Commune : Saint-Brandan (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.

In [63]:
df_region = pd.read_csv("pharmacies_par_region/pharmacies_bretagne.csv", sep=";")
df_avis = pd.read_csv("avis_bretagne.csv", sep=";", encoding="utf-8-sig")

total_pharmacies = df_region["result_label"].nunique()
compte_par_adresse = df_avis.groupby("adresse_pharmacie").size()
adresses_scrapees = set(compte_par_adresse.index)
nb_scrapees = len(adresses_scrapees)
nb_avec_0_avis = total_pharmacies - nb_scrapees
nb_avec_10_avis = (compte_par_adresse == 10).sum()

print("Total pharmacies :", total_pharmacies)
print(f"Pharmacies scrapees : {nb_scrapees} / {total_pharmacies}")
print("Pharmacies avec 0 avis :", nb_avec_0_avis)
print("Pharmacies avec 10 avis :", nb_avec_10_avis)

Total pharmacies : 952
Pharmacies scrapees : 794 / 952
Pharmacies avec 0 avis : 158
Pharmacies avec 10 avis : 9

## Region 5 : Corse

In [66]:
await scraper_une_region(
    fichier_region="pharmacies_par_region/pharmacies_corse.csv",
    fichier_sortie="avis_corse.csv",
    nb_pages_parallele=4,
)

Region : pharmacies_par_region/pharmacies_corse.csv
Nombre total de communes : 53
[1/53] Commune : Bastia (20 pharmacies)
2 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie du Fango : 6 avis recuperes
  Resultat suspect (10 avis) pour Pharmacie de l'Opéra, nouvelle tentative...
Pharmacie Pharmacie Ricci-Luciani : 15 avis recuperes
Pharmacie Pharmacie Dussol : 24 avis recuperes
Pharmacie Pharmacie Luccioni : 17 avis recuperes
Pharmacie Aprium Pharmacie du Palais : 17 avis recuperes
Pharmacie Pharmacie de l'Opéra : 10 avis recuperes
Pharmacie Pharmacie Notre-Dame de Lourdes : 9 avis recuperes
Pharmacie Pharmacie de la Place d'Armes : 41 avis recuperes
Pharmacie Gianvity : 9 avis recuperes
Pharmacie Pharmacie St Pierre : 71 avis recuperes
Pharmacie Pharmacie Santa Maria : 15 avis recuperes
Pharmacie Pharmacie Aurore : 7 avis recuperes
Pharmacie Pharmacie Saint-Roch : 9 avis recuperes
Pharmacie Pharmacie Balesi : 92 avis recuperes
Pharmacie Pharmacie Dominici : 126 avis recuperes
Pharmacie Pharmacie Principale : 13 avis recuperes
Pharmacie Pharmacie Centrale : 36 avis recuperes
Pharmacie Alfonsi - Port Toga : 215 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[2/53] Commune : Lucciana (3 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie de Lucciana : 85 avis recuperes
Pharmacie Pharmacie de Casamozza : 46 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[3/53] Commune : Corte (2 pharmacies)
Pharmacie Pharmacie Manzi : 26 avis recuperes
Pharmacie Pharmacie du Rond Point : 141 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[4/53] Commune : Morosaglia (2 pharmacies)
Pharmacie Pharmacie Guidicelli : 5 avis recuperes
Pharmacie Pharmacie Leon : 42 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[5/53] Commune : Ajaccio (21 pharmacies)
7 pharmacie(s) ignoree(s) car sans nom renseigne.
  Resultat suspect (10 avis) pour totum pharmcie, nouvelle tentative...
Pharmacie Pharmacie du Diamant : 33 avis recuperes
Pharmacie Lafayette : 25 avis recuperes
Pharmacie totum pharmcie : 14 avis recuperes
Pharmacie Pharmacie du Cours : 26 avis recuperes
Pharmacie Pharmacie des Plages : 24 avis recuperes
Pharmacie Pharmacie Poli : 4 avis recuperes
Pharmacie Pharmacie Rolland : 34 avis recuperes
Pharmacie Albert 1er : 0 avis recuperes
Pharmacie Pharmacie du Palais : 4 avis recuperes
Pharmacie Grande Pharmacie des Salines : 230 avis recuperes
Pharmacie Pharmacie Rolland : 34 avis recuperes
Pharmacie Pharmacie du Soleil : 17 avis recuperes
Pharmacie Pharmacie de la Préfecture : 21 avis recuperes
Pharmacie Pharmacie Principale : 29 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[6/53] Commune : San-Martino-di-Lota (1 pharmacies)
Pharmacie Pharmacie de Pietranera : 29 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[7/53] Commune : Sartène (1 pharmacies)
Pharmacie Pharmacie Du Rond Point : 23 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[8/53] Commune : Bonifacio (1 pharmacies)
Pharmacie Pharmacie Buzzo : 0 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[9/53] Commune : L'Île-Rousse (3 pharmacies)
Pharmacie Pharmacie du Marché : 33 avis recuperes
Pharmacie Pharmacie Savelli : 79 avis recuperes
Pharmacie Broche Rossellini Leadersanté : 109 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[10/53] Commune : Propriano (2 pharmacies)
Pharmacie Pharmacie ROYER : 7 avis recuperes
Pharmacie Matériel médical du Valinco : 118 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[11/53] Commune : Brando (1 pharmacies)
Pharmacie Pharmacie du Cap : 27 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[12/53] Commune : Penta-di-Casinca (2 pharmacies)
Pharmacie Pharmacie Filippi Gaziello : 54 avis recuperes
Pharmacie E.Leclerc Parapharmacie : 46 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[13/53] Commune : Calvi (2 pharmacies)
Pharmacie Pharmacie de la Plage : 48 avis recuperes
Pharmacie Pharmacie Centrale : 107 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[14/53] Commune : Cervione (1 pharmacies)
Pharmacie Pharmacie Simonpaoli : 21 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[15/53] Commune : Porto-Vecchio (5 pharmacies)
Pharmacie Pharmacie de la Marine : 52 avis recuperes
Pharmacie Pharmacie Nouvelle : 124 avis recuperes
Pharmacie Medical 2A : 2 avis recuperes
Pharmacie Pharmacie des 4 Chemins : 276 avis recuperes
Pharmacie Pharmacie Paolini : 586 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[16/53] Commune : Furiani (1 pharmacies)
Pharmacie Pharmacie de la Rocade : 65 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[17/53] Commune : Grosseto-Prugna (1 pharmacies)
Pharmacie Pharmacie Porticcio : 162 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[18/53] Commune : Ville-di-Pietrabugno (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[19/53] Commune : Ota (1 pharmacies)
Pharmacie Pharmacie de Porto : 37 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[20/53] Commune : Serra-di-Ferro (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[21/53] Commune : Cargèse (1 pharmacies)
Pharmacie Pharmacie Bianchi : 32 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[22/53] Commune : Calcatoggio (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[23/53] Commune : Prunelli-di-Fiumorbo (1 pharmacies)
Pharmacie Pharmacie Taddei : 85 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[24/53] Commune : Aléria (2 pharmacies)
2 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[25/53] Commune : Venaco (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[26/53] Commune : Sari-Solenzara (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[27/53] Commune : Olmeto (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[28/53] Commune : Lumio (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[29/53] Commune : Biguglia (2 pharmacies)
Pharmacie Pharmacie Pasqualini : 23 avis recuperes
Pharmacie Pharmacie Alfonsi-Biguglia : 598 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[30/53] Commune : Zonza (1 pharmacies)
Pharmacie Pharmacie Bartoli : 137 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[31/53] Commune : Saint-Florent (2 pharmacies)
Pharmacie Pharmacie Franceschini : 39 avis recuperes
Pharmacie Pharmacie de la Conca d'Oru : 36 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[32/53] Commune : Figari (1 pharmacies)
Pharmacie Pharmacie Roux : 32 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[33/53] Commune : Ventiseri (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[34/53] Commune : Alata (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[35/53] Commune : Ghisonaccia (2 pharmacies)
Pharmacie Pharmacie Beissy : 21 avis recuperes
Pharmacie Pharmacie Santoni : 68 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[36/53] Commune : Belgodère (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[37/53] Commune : Santa-Maria-di-Lota (1 pharmacies)
Pharmacie Pharmacie de la Tour : 17 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[38/53] Commune : San-Giuliano (1 pharmacies)
Pharmacie Pharmacie du Phare : 34 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[39/53] Commune : Borgo (3 pharmacies)
Pharmacie Pharmacie Le Bigot : 58 avis recuperes
Pharmacie Pharmacie La Marana : 23 avis recuperes
Pharmacie Pharmacie Muracciole : 53 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[40/53] Commune : Sarrola-Carcopino (1 pharmacies)
Pharmacie Pharmacie de Sarrola : 58 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[41/53] Commune : Calacuccia (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[42/53] Commune : Afa (1 pharmacies)
Pharmacie Pharmacie Afa Village : 29 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[43/53] Commune : Vico (2 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Pharmacie Pharmacie Marcaggi Totum : 35 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[44/53] Commune : Peri (1 pharmacies)
Pharmacie Pharmacie Casabianca : 56 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[45/53] Commune : Calenzana (1 pharmacies)
Pharmacie Pharmacie Albano Moretti : 21 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[46/53] Commune : Venzolasca (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[47/53] Commune : Cozzano (1 pharmacies)
Pharmacie Pharmacie Alvau : 0 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[48/53] Commune : Luri (1 pharmacies)
Pharmacie Pharmacie de Luri : 25 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[49/53] Commune : Sainte-Lucie-de-Tallano (1 pharmacies)
1 pharmacie(s) ignoree(s) car sans nom renseigne.
Lot traite. Fichier sauvegarde : avis_corse.csv
[50/53] Commune : Levie (1 pharmacies)
Pharmacie Pharmacie U Piratu : 0 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[51/53] Commune : Rogliano (1 pharmacies)
Pharmacie Pharmacie de la Giraglia : 40 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[52/53] Commune : San-Nicolao (1 pharmacies)
Pharmacie Pharmacie Simoni : 47 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
[53/53] Commune : Vescovato (1 pharmacies)
Pharmacie Pharmacie Papi Stefani : 36 avis recuperes
Lot traite. Fichier sauvegarde : avis_corse.csv
Scraping termine pour : pharmacies_par_region/pharmacies_corse.csv

In [67]:
df_region = pd.read_csv("pharmacies_par_region/pharmacies_corse.csv", sep=";")
df_avis = pd.read_csv("avis_corse.csv", sep=";", encoding="utf-8-sig")

total_pharmacies = df_region["result_label"].nunique()
compte_par_adresse = df_avis.groupby("adresse_pharmacie").size()
adresses_scrapees = set(compte_par_adresse.index)
nb_scrapees = len(adresses_scrapees)
nb_avec_0_avis = total_pharmacies - nb_scrapees
nb_avec_10_avis = (compte_par_adresse == 10).sum()

print("Total pharmacies :", total_pharmacies)
print(f"Pharmacies scrapees : {nb_scrapees} / {total_pharmacies}")
print("Pharmacies avec 0 avis :", nb_avec_0_avis)
print("Pharmacies avec exactement 10 avis :", nb_avec_10_avis)

Total pharmacies : 112
Pharmacies scrapees : 82 / 112
Pharmacies avec 0 avis : 30
Pharmacies avec exactement 10 avis : 1

# Autres régions : 
## Region 6 : Ile de France

In [ ]:
# await scraper_une_region(
#     fichier_region="pharmacies_par_region/pharmacies_ile_de_france.csv",
#     fichier_sortie="avis_ile_de_france.csv",
#     nb_pages_parallele=4,
# )

## Région 7 : Normandie

In [ ]:
# await scraper_une_region(
#     fichier_region="pharmacies_par_region/pharmacies_normandie.csv",
#     fichier_sortie="avis_normandie.csv",
#     nb_pages_parallele=4,
# )

## Région 8 : Hauts de France

In [ ]:
# await scraper_une_region(
#     fichier_region="pharmacies_par_region/pharmacies_hauts_de_france.csv",
#     fichier_sortie="avis_hauts_de_france.csv",
#     nb_pages_parallele=4,
# )

## Région 9 : Grand Est

In [ ]:
# await scraper_une_region(
#     fichier_region="pharmacies_par_region/pharmacies_grand_est.csv",
#     fichier_sortie="avis_grand_est.csv",
#     nb_pages_parallele=3,
# )

## Région 10 : Pays de la Loire

In [ ]:
# await scraper_une_region(
#     fichier_region="pharmacies_par_region/pharmacies_pays_de_la_loire.csv",
#     fichier_sortie="avis_pays_de_la_loire.csv",
#     nb_pages_parallele=4,
# )

## Région 11 : Nouvelle Aquitaine

In [ ]:
# await scraper_une_region(
#     fichier_region="pharmacies_par_region/pharmacies_nouvelle_aquitaine.csv",
#     fichier_sortie="avis_nouvelle_aquitaine.csv",
#     nb_pages_parallele=4,
# )

## Région 12 : Occitanie

In [ ]:
# await scraper_une_region(
#     fichier_region="pharmacies_par_region/pharmacies_occitanie.csv",
#     fichier_sortie="avis_occitanie.csv",
#     nb_pages_parallele=4,
# )

## Région 13 : Provence Alpes Côtes d'Azur

In [ ]:
# await scraper_une_region(
#     fichier_region="pharmacies_par_region/pharmacies_provence_alpes_cote_d_azur.csv",
#     fichier_sortie="avis_provence_alpes_cote_d_azur.csv",
#     nb_pages_parallele=4,
# )