# PARTIE 2 : Nettoyage + pre processing

Objectisf :
- Assemblage des fichier csv et homogénéisation fichiers CSV des autres collègues
- nettoyage pour étape de pré processing pour NLP.

In [1]:
import pandas as pd
import os

## ETAPE 1 : Assemblage et homogénéisation 

### Fusion fichier Flora

In [2]:
# Ajout de la variable "region" pour mes fichiers
# Pour coïncider avec les autres fichiers
dossier = "avis_regions"

fichiers_et_regions = {
    "avis_auvergne_rhone_alpes_FINAL.csv": "Auvergne-Rhone-Alpes",
    "avis_bourgogne_franche_comte.csv": "Bourgogne-Franche-Comte",
    "avis_centre_val_de_loire.csv": "Centre-Val de Loire",
    "avis_bretagne.csv": "Bretagne",
    "avis_corse.csv": "Corse",}

for nom_fichier, nom_region in fichiers_et_regions.items():
    chemin_fichier = os.path.join(dossier, nom_fichier)
    if os.path.exists(chemin_fichier):
        df = pd.read_csv(chemin_fichier, sep=";", encoding="utf-8-sig")
        df["region"] = nom_region
        df.to_csv(chemin_fichier, sep=";", index=False, encoding="utf-8-sig")
        print(f"{chemin_fichier} : colonne 'region' ajoutee ({nom_region}), {len(df)} lignes")
    else:
        print(f"{chemin_fichier} : introuvable, ignore")

avis_regions\avis_auvergne_rhone_alpes_FINAL.csv : colonne 'region' ajoutee (Auvergne-Rhone-Alpes), 143660 lignes
avis_regions\avis_bourgogne_franche_comte.csv : colonne 'region' ajoutee (Bourgogne-Franche-Comte), 36300 lignes
avis_regions\avis_centre_val_de_loire.csv : colonne 'region' ajoutee (Centre-Val de Loire), 28759 lignes
avis_regions\avis_bretagne.csv : colonne 'region' ajoutee (Bretagne), 33398 lignes
avis_regions\avis_corse.csv : colonne 'region' ajoutee (Corse), 5180 lignes

In [3]:
dossier = "avis_regions"

fichiers_a_fusionner_Flo = [
    "avis_auvergne_rhone_alpes_FINAL.csv",
    "avis_bourgogne_franche_comte.csv",
    "avis_centre_val_de_loire.csv",
    "avis_bretagne.csv",
    "avis_corse.csv"
]

In [4]:
morceaux_Flo = []
for fichier in fichiers_a_fusionner_Flo:
    chemin_fichier = os.path.join(dossier, fichier)
    if os.path.exists(chemin_fichier):
        df = pd.read_csv(chemin_fichier, sep=";", encoding="utf-8-sig")
        morceaux_Flo.append(df)
        print(f"{chemin_fichier} : {len(df)} lignes")
    else:
        print(f"{chemin_fichier} : introuvable, ignore")

df_regions_Flo = pd.concat(morceaux_Flo, ignore_index=True)
print("\nTotal fusion :", len(df_regions_Flo), "lignes")

avis_regions\avis_auvergne_rhone_alpes_FINAL.csv : 143660 lignes
avis_regions\avis_bourgogne_franche_comte.csv : 36300 lignes
avis_regions\avis_centre_val_de_loire.csv : 28759 lignes
avis_regions\avis_bretagne.csv : 33398 lignes
avis_regions\avis_corse.csv : 5180 lignes

Total fusion : 247297 lignes

In [5]:
chemin_sortie = os.path.join(dossier, "avis_regions_Flo.csv")
df_regions_Flo.to_csv(chemin_sortie, sep=";", index=False, encoding="utf-8-sig")
print("Fichier sauvegarde :", chemin_sortie)

Fichier sauvegarde : avis_regions\avis_regions_Flo.csv

### Fusion fichiers Louise

In [6]:
fichiers_a_fusionner_Louise = [
    "avis_ile_de_france.csv",
    "avis_hauts_de_france.csv",
    "avis_grand_est.csv",
    "avis_normandie.csv"
]

In [7]:
morceaux_Louise = []
for fichier in fichiers_a_fusionner_Louise:
    chemin_fichier = os.path.join(dossier, fichier)
    if os.path.exists(chemin_fichier):
        df = pd.read_csv(chemin_fichier, sep=";", encoding="utf-8-sig")
        morceaux_Louise.append(df)
        print(f"{chemin_fichier} : {len(df)} lignes")
    else:
        print(f"{chemin_fichier} : introuvable, ignore")

df_regions_Louise = pd.concat(morceaux_Louise, ignore_index=True)
print("\nTotal fusion :", len(df_regions_Louise), "lignes")

avis_regions\avis_ile_de_france.csv : 124776 lignes
avis_regions\avis_hauts_de_france.csv : 55542 lignes
avis_regions\avis_grand_est.csv : 48224 lignes
avis_regions\avis_normandie.csv : 32871 lignes

Total fusion : 261413 lignes

In [8]:
chemin_sortie = os.path.join(dossier, "avis_regions_Louise.csv")
df_regions_Louise.to_csv(chemin_sortie, sep=";", index=False, encoding="utf-8-sig")
print("Fichier sauvegarde :", chemin_sortie)

Fichier sauvegarde : avis_regions\avis_regions_Louise.csv

## Partie fichier Flo
Pour homogénéiser nos fichiers, je me base sur mes fichiers : <br> 
Variables à garder : 
- FID : colonne 0
- nom_pharmacie : colonne 1 
- note_avis : colonne 2
- texte_avis : colonne 3
- date_avis_texte : colonne 4
- date_avis_estimee : colonne 5
- texte_reponse : colonne 6
- date_response_texte : colonne 7
- date_reponse_estimee : colonne 8
- region : colonne 9

Variables à supprimer : 
- adresse_pharmacie
- review_id

In [9]:
df_regions_Flo = df_regions_Flo.drop(columns=['adresse_pharmacie', 'review_id'])

In [10]:
df_regions_Flo.sample(n=3)

,FID,nom_pharmacie,note_avis,texte_avis,date_avis_texte,date_avis_estimee,texte_reponse,date_reponse_texte,date_reponse_estimee,region
5470,pharmacies_point.268130819,Pharmacie du 6ème,5.0,Très bonne pharmacie avec une équipe très agré...,il y a 2 ans,2024-06-20,NaN,NaN,NaN,Auvergne-Rhone-Alpes
210128,pharmacies_point.4568924123,La Pharmacie Verte,5.0,Au top cette pharmacie. Je suis une fidèle dep...,il y a un an,2025-06-24,NaN,NaN,NaN,Bretagne
210168,pharmacies_point.7434326651,Pharmacie des Orières,1.0,Exactement l’opposé d’une pharmacie de proximi...,il y a un mois,2026-05-25,NaN,NaN,NaN,Bretagne

In [11]:
colonnes = ['date_avis_estimee', 'date_reponse_estimee']
df_regions_Flo[colonnes] = df_regions_Flo[colonnes].replace('-', '/', regex=True)
df_regions_Flo[colonnes].sample(4)

       date_avis_estimee date_reponse_estimee
204988        2021/06/26           2021/06/26
153029        2025/06/23           2025/06/23
45098         2025/06/20                  NaN
74246         2022/06/22                  NaN

In [12]:
df_regions_Flo.sample(3)

,FID,nom_pharmacie,note_avis,texte_avis,date_avis_texte,date_avis_estimee,texte_reponse,date_reponse_texte,date_reponse_estimee,region
129867,pharmacies_point.926332915,Pharmacie Gambetta,5.0,Tout d'abord il faut remarquer la dimension et...,il y a 4 ans,2022/06/23,NaN,NaN,NaN,Auvergne-Rhone-Alpes
151710,pharmacies_point.13406697752,Pharmacie des Tilleroyes,4.0,"Bonne pharmacie, aimable, bien renseigné avec ...",il y a un an,2025/06/23,NaN,NaN,NaN,Bourgogne-Franche-Comte
80972,pharmacies_point.5462801799,Pharmacie de Lissieu,1.0,Les prix sont juste abusé\nLe sirop de bebe es...,il y a 6 ans,2020/06/22,NaN,NaN,NaN,Auvergne-Rhone-Alpes

In [13]:
chemin_sortie = os.path.join(dossier, "avis_Flo_propre.csv")
df_regions_Flo.to_csv(chemin_sortie, sep=";", index=False, encoding="utf-8-sig")
print("Fichier sauvegarde :", chemin_sortie)

Fichier sauvegarde : avis_regions\avis_Flo_propre.csv

## Partie fichier Louise

Variables à garder : 
- FID // 
- Nom_pharmacie → changer le nom : nom_pharmacie 
- Region → mettre en position 10 + changer le nom : region 
- Note_Avis → changer le nom : note_avis 
- Date_Avis_Brute → date_avis_texte 
- Date_Avis_Calculee → date_avis_estimee 
- Date_Reponse_Brute → colonne 8 + nom change : date_response_texte 
- Date_Reponse Calculee → colonne 9 + nom change : date_reponse_estimee 
- Texte_Avis → mettre en 4e position + changer le nom : texte_avis
- Response_Titulaire → colonne 7 + changer le nom :  date_response_texte 

Variables à supprimer : 
- Ville
- Note Globale

In [14]:
df_regions_Louise = df_regions_Louise.drop(columns=['Ville', 'Note_Globale'])
df_regions_Louise.sample(n=3)

,FID,Nom_Pharmacie,Region,Note_Avis,Date_Avis_Brute,Date_Avis_Calculee,Date_Reponse_Brute,Date_Reponse_Calculee,Texte_Avis,Reponse_Titulaire
119155,pharmacies_point.10660683182,Pharmacie Grimaux Parmentier,Dep_95,3.0,il y a 3 ans,25/06/2023,NaN,NaN,"Je suis venu pour du Doliprane, je reste mitig...",NaN
258967,pharmacies_point.7001867935,Pharmacie Saint-Gilles,Normandie,5.0,il y a 4 ans,24/06/2022,NaN,NaN,Toujours souriante et aimable. Merci pour tout...,NaN
84667,pharmacies_point.574874556,Pharmacie de l'Hôtel de Ville,Dep_93_94,4.0,il y a 8 ans,25/06/2018,il y a 8 ans,25/06/2018,"Équipes super,bonne accueil","Elisabeth, Vos étoiles éclairent magnifiquemen..."

In [15]:
# Renomme les variables
df_regions_Louise = df_regions_Louise.rename(columns={
    'Nom_Pharmacie': 'nom_pharmacie',
    'Region': 'region',
    'Note_Avis': 'note_avis',
    'Date_Avis_Brute': 'date_avis_texte',
    'Date_Avis_Calculee': 'date_avis_estimee',
    'Date_Reponse_Brute': 'date_reponse_texte',
    'Date_Reponse_Calculee': 'date_reponse_estimee',
    'Texte_Avis': 'texte_avis',
    'Reponse_Titulaire': 'texte_reponse'
})
df_regions_Louise.sample(n=3)

,FID,nom_pharmacie,region,note_avis,date_avis_texte,date_avis_estimee,date_reponse_texte,date_reponse_estimee,texte_avis,texte_reponse
218815,pharmacies_point.651716236,NaN,Grand Est,5.0,il y a un an,23/06/2025,il y a un an,23/06/2025,Tres bon service,"Bonjour Madame/Monsieur, merci pour votre comm..."
24456,pharmacies_point.663236746,Pharmacie Courcelles - Demours,Paris_75,5.0,il y a 8 ans,24/06/2018,NaN,NaN,"Personnel tres competent, tres bons conseils e...",NaN
250688,pharmacies_point.4252110982,Pharmacie du Clos Herbert,Normandie,5.0,il y a 4 mois,24/02/2026,NaN,NaN,"Personnel au top bons conseils sympathiques ,M...",NaN

In [16]:
df_regions_Louise["region"].value_counts()

region
Grand Est       48224
Dep_91_92       37240
Dep_59_62       34806
Normandie       32871
Paris_75        32867
Dep_93_94       28340
Dep_02_60_80    20736
Dep_77          14290
Dep_95          12038
Name: count, dtype: int64

In [17]:
#Corresction variable région
corrections = {
    'Dep_59_62': 'Hauts-de-France',
    'Dep_02_60_80': 'Hauts-de-France',
    'Dep_91_92': 'Ile-de-France',
    'Paris_75': 'Ile-de-France',
    'Dep_93_94': 'Ile-de-France',
    'Dep_77': 'Ile-de-France',
    'Dep_95': 'Ile-de-France',
    'Chir': 'Ile-de-France'
}

df_regions_Louise['region'] = df_regions_Louise['region'].replace(corrections, regex=True)

In [18]:
colonne_region = df_regions_Louise.pop('region')
df_regions_Louise.insert(9, 'region', colonne_region)
df_regions_Louise.sample(4)

,FID,nom_pharmacie,note_avis,date_avis_texte,date_avis_estimee,date_reponse_texte,date_reponse_estimee,texte_avis,texte_reponse,region
124822,pharmacies_point.64864035,Pharmacie Nigault,5.0,il y a un an,26/06/2025,NaN,NaN,(Aucun texte),NaN,Hauts-de-France
29843,pharmacies_point.1128854283,Pharmacie des Grands Boulevards,5.0,il y a 5 mois,24/01/2026,NaN,NaN,Equipe très agréable qui m'ont aider à trouver...,NaN,Ile-de-France
207997,pharmacies_point.617281438,Pharmacie du Vélo,5.0,il y a 4 mois,23/02/2026,NaN,NaN,"Excellent service , accueil souriant et agréab...",NaN,Grand Est
95429,pharmacies_point.3557801639,Pharmacie Roustan,5.0,il y a 2 ans,25/06/2024,il y a un an,25/06/2025,Grande pharmacie avec du choix au top ! Équipe...,🙏🏻🙏🏻🙏🏻 Merci beaucoup pour vos encouragements ...,Ile-de-France

In [19]:
colonne_texte_avis = df_regions_Louise.pop('texte_avis')
df_regions_Louise.insert(3, 'texte_avis', colonne_texte_avis)
df_regions_Louise.sample(4)

,FID,nom_pharmacie,note_avis,texte_avis,date_avis_texte,date_avis_estimee,date_reponse_texte,date_reponse_estimee,texte_reponse,region
163517,pharmacies_point.2980129466,Pharmacie Saint-Victor,2.0,"Décevant, après une commande internet pour 10 ...",il y a un an,26/06/2025,il y a un an,26/06/2025,"Bonjour, Merci d’avoir pris le temps de partag...",Hauts-de-France
236024,pharmacies_point.13185862838,Pharmacie de la Charentonne,5.0,Superbe pharmacie avec un large choix de produ...,Modifié il y a 3 ans,24/06/2023,il y a 4 ans,24/06/2022,Merci 🙏 …,Normandie
20882,pharmacies_point.494658847,Pharmacie Plaisance,5.0,Accueil et aide super aimable des personnes Ch...,il y a un an,24/06/2025,NaN,NaN,NaN,Ile-de-France
16404,pharmacies_point.2394027666,Pharmacie Tran,NaN,Aucun avis,NaN,NaN,NaN,NaN,NaN,Ile-de-France

In [20]:
colonne_date_reponse_texte = df_regions_Louise.pop('texte_reponse')
df_regions_Louise.insert(6, 'texte_reponse', colonne_date_reponse_texte)
df_regions_Louise.sample(4)

,FID,nom_pharmacie,note_avis,texte_avis,date_avis_texte,date_avis_estimee,texte_reponse,date_reponse_texte,date_reponse_estimee,region
93611,pharmacies_point.2696617306,Pharmacie des 4 Routes,1.0,"Je suis allée dans cette pharmacie hier, le p...",il y a 3 ans,25/06/2023,"Bonjour, Nous sommes désolés pour cette expéri...",il y a un an,25/06/2025,Ile-de-France
175302,pharmacies_point.462752893,Pharmacie Saint-Germain,5.0,Tres bonne pharmacie Personnels tres agréable,il y a un an,26/06/2025,Merci beacoup M. Piran pour votre commentaire ...,il y a un an,26/06/2025,Hauts-de-France
193932,pharmacies_point.7351222752,Pharmacie des Argonautes,5.0,Réorienté par le 15 ne pouvant rien faire dans...,il y a 8 ans,23/06/2018,"Bonjour Madame, je vous remercie pour votre co...",il y a 8 ans,23/06/2018,Grand Est
77956,pharmacies_point.3330751349,Aprium Pharmacie de l'Europe,1.0,Désagréables...,il y a 3 ans,25/06/2023,NaN,NaN,NaN,Ile-de-France

In [21]:
df_regions_Flo.sample(4)

,FID,nom_pharmacie,note_avis,texte_avis,date_avis_texte,date_avis_estimee,texte_reponse,date_reponse_texte,date_reponse_estimee,region
91271,pharmacies_point.2065301225,Pharmacie Belle Étoile,5.0,Un geste qui compte : notre expérience à la ph...,Modifié il y a 4 mois,2026/02/21,NaN,NaN,NaN,Auvergne-Rhone-Alpes
170315,pharmacies_point.3168901197,Pharmacie de Thoirette,5.0,"Une équipe pro, à l'écoute qui tente toujours ...",il y a 4 ans,2022/06/24,NaN,NaN,NaN,Bourgogne-Franche-Comte
113747,pharmacies_point.224184051,Pharmacie du Printemps,5.0,"Très bon accueil, bons conseils.",il y a un an,2025/06/22,"Merci Madame, nous faisons de notre mieux pour...",il y a un an,2025/06/22,Auvergne-Rhone-Alpes
39253,pharmacies_point.2813904228,Pharmacie du Creux,5.0,Très bien,il y a 4 ans,2022/06/21,NaN,NaN,NaN,Auvergne-Rhone-Alpes

In [22]:
chemin_sortie = os.path.join(dossier, "avis_Louise_propre.csv")
df_regions_Louise.to_csv(chemin_sortie, sep=";", index=False, encoding="utf-8-sig")
print("Fichier sauvegarde :", chemin_sortie)

Fichier sauvegarde : avis_regions\avis_Louise_propre.csv

In [23]:
df_1 = pd.read_csv(os.path.join(dossier, "avis_Flo_propre.csv"), sep=";", encoding="utf-8-sig")
df_2 = pd.read_csv(os.path.join(dossier, "avis_Louise_propre.csv"), sep=";", encoding="utf-8-sig")

print(list(df_1.columns) == list(df_2.columns))

True

## Fusion des 2 fichers

In [24]:
df_1 = pd.read_csv(os.path.join(dossier, "avis_Flo_propre.csv"), sep=";", encoding="utf-8-sig")
df_2 = pd.read_csv(os.path.join(dossier, "avis_Louise_propre.csv"), sep=";", encoding="utf-8-sig")

df_final = pd.concat([df_1, df_2], ignore_index=True)

print("Total fusionne :", len(df_final), "lignes")

chemin_sortie = os.path.join(dossier, "avis_complet.csv")
df_final.to_csv(chemin_sortie, sep=";", index=False, encoding="utf-8-sig")
print("Fichier sauvegarde :", chemin_sortie)

Total fusionne : 508710 lignes
Fichier sauvegarde : avis_regions\avis_complet.csv

In [25]:
# Vérifications 
df_final.sample(4)

,FID,nom_pharmacie,note_avis,texte_avis,date_avis_texte,date_avis_estimee,texte_reponse,date_reponse_texte,date_reponse_estimee,region
344403,pharmacies_point.4701790608,Pharmacie des Presles,4.0,très gentille,il y a 2 ans,25/06/2024,Merci pour votre avis et votre confiance. Votr...,il y a 4 mois,25/02/2026,Ile-de-France
494989,pharmacies_point.2336670908,Pharmacie du Progrès,5.0,(Aucun texte),il y a 5 ans,24/06/2021,NaN,NaN,NaN,Normandie
198796,pharmacies_point.2350876151,Pharmacie du carré d'or,4.0,NaN,il y a 6 mois,2025/12/27,NaN,NaN,NaN,Centre-Val de Loire
97742,pharmacies_point.3242801744,Pharmacie Bourdelle Seychal,3.0,"Pharmacie simple et ordinaire, jamais de cadeaux.",il y a 9 ans,2017/06/23,NaN,NaN,NaN,Auvergne-Rhone-Alpes

In [26]:
df_final.nunique()

FID                      11060
nom_pharmacie             7720
note_avis                    7
texte_avis              346677
date_avis_texte            123
date_avis_estimee          310
texte_reponse           137033
date_reponse_texte          96
date_reponse_estimee       260
region                       9
dtype: int64

In [27]:
df_final["region"].value_counts()

region
Auvergne-Rhone-Alpes       143660
Ile-de-France              124775
Hauts-de-France             55542
Grand Est                   48224
Bourgogne-Franche-Comte     36300
Bretagne                    33398
Normandie                   32871
Centre-Val de Loire         28759
Corse                        5180
Name: count, dtype: int64

In [28]:
df_final["note_avis"].value_counts()

note_avis
5.0       350912
1.0        78320
4.0        50001
3.0        15242
2.0        11634
1980.0         1
0.0            1
Name: count, dtype: int64

In [29]:
df_final = df_final[~df_final["note_avis"].isin([1980.0, 0.0])]
print("Nombre de lignes restantes :", len(df_final))

Nombre de lignes restantes : 508708

In [30]:
df_final["note_avis"].value_counts()

note_avis
5.0    350912
1.0     78320
4.0     50001
3.0     15242
2.0     11634
Name: count, dtype: int64

**DONC** : fichier csv avis_complet.csv, on retrouve les régions : 
- Auvergne Rhône Alpes
- Bourgogne Franche Comté
- Centre Val de Loire
- Bretagne
- Corse
- Ile de France
- Hauts de france
- Grand Est
- Normandie

Régions manquante à ce jour (29/06/26)
- Nouvelle Aquitaine
- Occitanie
- Pays de la Loire
- Provence Alpes Côte d'Azur

## ETAPE 2 : Nettoyage + PRE-PROCESSING (variable `texte_avis` = commentaire)
> pour NLP on se base sur les émotions 
- dédupliquer les avis
- retirer/normaliser les espaces multiple / retour à la ligne
- convertir les émoji en tokens texte type (`content` : via une lib comme `emoji`
- garder les MAJ (= émotion fort) et ponctuation (! et ?)
- on va pas retirer les stop words
- On ne lemmatise pas si on use CamemBERT/ LLM qui gère forme dléchies nativement
- Créer une colonne séparée longueur_avis et a_emoji en features additionnelles : utile pour croiser avec le sentiment
- gère les cas note sans texte -> sentiment basé uniquement sur l'étoile
- Gérer le cas "texte contredit la note" (ton objectif) → garder les deux colonnes séparées (sentiment_etoile, sentiment_texte) pour comparer, ne surtout pas les fusionner en amont


#### Supprime les valeurs manquantes : NaN / (Aucun Texte) / Aucun Avis

In [31]:
total_lignes = df_final['texte_avis'].str.contains('Aucun Texte', case=False, na=False).sum()
print(f"Nombre de lignes contenant le mot : {total_lignes}")

Nombre de lignes contenant le mot : 61324

In [32]:
total_lignes = df_final['texte_avis'].str.contains('NaN', case=False, na=False).sum()
print(f"Nombre de lignes contenant le mot : {total_lignes}")

Nombre de lignes contenant le mot : 23730

In [33]:
total_lignes = df_final['texte_avis'].str.contains('Aucun Avis', case=False, na=False).sum()
print(f"Nombre de lignes contenant le mot : {total_lignes}")

Nombre de lignes contenant le mot : 1624

In [35]:
mots_a_vider = 'NaN|Aucun Avis|Aucun Texte'

# symbole "~" permet de ne garder que ce qui ne contient pas ces mots
df_final['texte_avis'] = df_final['texte_avis'].str.replace(mots_a_vider, '', case=False, regex=True)

In [36]:
total = df_final['texte_avis'].str.contains(mots_a_vider, case=False, na=False).sum()
print(f"Nombre total de lignes ces mots : {total}")

Nombre total de lignes ces mots : 0

In [37]:
df_final.shape

(508708, 10)

**Remarque : on supprime pour la région Auvergne les pharmacies dont les noms ne sont pas connus, car lors du scrapping > scrappe les mauvais établissements**

In [38]:
filtre_vides_auvergne = (df_final['region'].str.contains('auvergne', case=False, na=False)) & (df_final['texte_avis'].isna())
total_a_supprimer = filtre_vides_auvergne.sum()

print(f"Nombre de lignes vides en Auvergne: {total_a_supprimer}")

Nombre de lignes vides en Auvergne: 29770

In [39]:
df_final = df_final[~filtre_vides_auvergne]
df_final.shape

(478938, 10)

In [40]:
df_final.to_csv(nom_fichier, index=False, encoding='utf-8')

...